import { getSupabase } from '@/lib/supabase';
import type { PaginatedResponse } from '@/types/api/api';
export interface Notification { id:string; userId:string; title:string; message:string; type:string; data?:Record<string,unknown>; isRead:boolean; actionUrl?:string; createdAt:string; }
export interface NotificationFilters { page?:number; limit?:number; isRead?:boolean; type?:string; }
const mapNotification=(row:any):Notification=>({id:String(row.id),userId:String(row.user_id),title:String(row.title||'Notification'),message:String(row.body||''),type:String(row.type||'info'),data:row.data&&typeof row.data==='object'?row.data:undefined,isRead:Boolean(row.read_at),actionUrl:row.action_url||undefined,createdAt:String(row.created_at||'')});
const requireUser=async()=>{const{data,error}=await getSupabase().auth.getUser();if(error||!data.user)throw new Error('You must be signed in');return data.user;};
export const fetchNotifications=async(filters:NotificationFilters={},_token?:string):Promise<PaginatedResponse<Notification>>=>{const user=await requireUser();const page=Math.max(1,filters.page||1),limit=Math.min(100,Math.max(1,filters.limit||20)),from=(page-1)*limit;let query=getSupabase().from('notifications').select('*',{count:'exact'}).eq('user_id',user.id);if(filters.isRead===true)query=query.not('read_at','is',null);if(filters.isRead===false)query=query.is('read_at',null);if(filters.type)query=query.eq('type',filters.type);const{data,error,count}=await query.order('created_at',{ascending:false}).range(from,from+limit-1);if(error)throw new Error(error.message);const total=count||0;return{data:(data||[]).map(mapNotification),page,pageSize:limit,total,totalPages:Math.max(1,Math.ceil(total/limit))};};
export const fetchUnreadNotifications=async(_token?:string)=>{const r=await fetchNotifications({page:1,limit:100,isRead:false});return{notifications:r.data,count:r.total};};
export const markNotificationAsRead=async(id:string,_token?:string)=>{const user=await requireUser();const{data,error}=await getSupabase().from('notifications').update({read_at:new Date().toISOString()}).eq('id',id).eq('user_id',user.id).select().maybeSingle();if(error)throw new Error(error.message);return{notification:data?mapNotification(data):null};};
export const markAllNotificationsAsRead=async(_token?:string)=>{const user=await requireUser();const{error}=await getSupabase().from('notifications').update({read_at:new Date().toISOString()}).eq('user_id',user.id).is('read_at',null);if(error)throw new Error(error.message);return{success:true};};
export const deleteNotification=async(id:string,_token?:string)=>{const user=await requireUser();const{error}=await getSupabase().from('notifications').delete().eq('id',id).eq('user_id',user.id);if(error)throw new Error(error.message);return{success:true};};
export const deleteAllNotifications=async(_token?:string)=>{const user=await requireUser();const{error}=await getSupabase().from('notifications').delete().eq('user_id',user.id);if(error)throw new Error(error.message);return{success:true};};
