'use client';

import React, { useEffect } from 'react';
import Link from 'next/link';
import { usePathname, useRouter } from 'next/navigation';
import { useAuth } from '@/contexts/AuthContext';
import { Home, BookOpen, GraduationCap as AcademicCapIcon, ClipboardCheck as ClipboardDocumentCheckIcon, MessageSquare as ChatBubbleLeftRightIcon, Bookmark as LibraryBookmarkIcon, Lightbulb as LightBulbIcon, Users as UserGroupIcon, Trophy, Bell, FileText as DocumentTextIcon, LogOut as ArrowLeftStartOnRectangleIcon, Menu as Bars3Icon, X as XMarkIcon, Settings as Cog6ToothIcon } from 'lucide-react';

const studentNavItems = [
  { label: 'Dashboard', href: '/dashboard', icon: Home }, { label: 'Courses', href: '/dashboard/courses', icon: BookOpen }, { label: 'Lessons', href: '/dashboard/lessons', icon: AcademicCapIcon }, { label: 'Exams', href: '/dashboard/exams', icon: ClipboardDocumentCheckIcon }, { label: 'Past Questions', href: '/dashboard/past-questions', icon: LibraryBookmarkIcon }, { label: 'AI Tutor', href: '/dashboard/ai/tutor', icon: LightBulbIcon }, { label: 'Flashcards', href: '/dashboard/flashcards', icon: AcademicCapIcon }, { label: 'Community', href: '/dashboard/community', icon: ChatBubbleLeftRightIcon }, { label: 'Progress', href: '/dashboard/progress', icon: Trophy }, { label: 'Reports', href: '/dashboard/reports', icon: DocumentTextIcon },
];
const teacherNavItems = [
  { label: 'Dashboard', href: '/dashboard', icon: Home }, { label: 'My Courses', href: '/dashboard/courses', icon: BookOpen }, { label: 'Lessons', href: '/dashboard/lessons', icon: AcademicCapIcon }, { label: 'Assignments', href: '/dashboard/assignments', icon: ClipboardDocumentCheckIcon }, { label: 'Students', href: '/dashboard/teacher', icon: UserGroupIcon }, { label: 'Earnings', href: '/dashboard/teacher', icon: Trophy }, { label: 'Reports', href: '/dashboard/teacher/report', icon: DocumentTextIcon },
];
const parentNavItems = [
  { label: 'Dashboard', href: '/dashboard', icon: Home }, { label: 'My Children', href: '/dashboard/parent', icon: UserGroupIcon }, { label: 'Progress', href: '/dashboard/progress', icon: Trophy }, { label: 'Results', href: '/dashboard/exams', icon: ClipboardDocumentCheckIcon }, { label: 'Notifications', href: '/dashboard/notifications', icon: Bell },
];

export default function DashboardLayout({ children }: { children: React.ReactNode }) {
  const pathname = usePathname(); const router = useRouter(); const { user, isAuthenticated, logout } = useAuth(); const [sidebarOpen, setSidebarOpen] = React.useState(false);
  useEffect(() => { if (!isAuthenticated && !pathname.startsWith('/login') && !pathname.startsWith('/register')) router.push('/login'); }, [isAuthenticated, pathname, router]);
  const navItems = user?.role === 'teacher' ? teacherNavItems : user?.role === 'parent' ? parentNavItems : studentNavItems;
  const handleLogout = async () => { await logout(); router.push('/login'); };
  const Brand = () => <Link href="/dashboard" aria-label="THE GUIDE dashboard" className="flex items-center gap-2"><img src="/logos/the-guide-mark.svg" alt="THE GUIDE" className="h-9 w-9 object-contain" /><span className="font-extrabold tracking-tight text-[#151A3A] dark:text-white">THE GUIDE</span></Link>;
  return <div className="min-h-screen bg-stone-50 dark:bg-[#151A3A]">
    <header className="fixed left-0 right-0 top-0 z-50 flex h-14 items-center justify-between border-b border-stone-200 bg-white px-4 dark:border-slate-700 dark:bg-[#151A3A] lg:hidden"><Brand /><button onClick={() => setSidebarOpen(!sidebarOpen)} className="rounded-lg p-2 text-slate-600 hover:bg-brand-50 hover:text-brand-700 dark:text-slate-300 dark:hover:bg-slate-800" aria-label="Toggle navigation">{sidebarOpen ? <XMarkIcon className="h-6 w-6" /> : <Bars3Icon className="h-6 w-6" />}</button></header>
    {sidebarOpen && <div className="fixed inset-0 z-40 bg-[#151A3A]/60 backdrop-blur-[1px] lg:hidden" onClick={() => setSidebarOpen(false)} />}
    <aside className={`fixed left-0 top-0 z-50 h-full w-64 transform border-r border-stone-200 bg-white transition-transform duration-200 dark:border-slate-700 dark:bg-[#151A3A] ${sidebarOpen ? 'translate-x-0' : '-translate-x-full'} lg:translate-x-0`}><div className="flex h-full flex-col"><div className="flex h-14 items-center border-b border-stone-100 px-4 dark:border-slate-700"><Brand /><button onClick={() => setSidebarOpen(false)} className="ml-auto rounded p-1 text-slate-500 hover:bg-brand-50 hover:text-brand-700 dark:hover:bg-slate-800 lg:hidden"><XMarkIcon className="h-5 w-5" /></button></div><nav className="flex-1 overflow-y-auto px-2 py-4"><div className="space-y-1">{navItems.map((item) => { const isActive = pathname === item.href || pathname.startsWith(`${item.href}/`); return <Link key={item.href} href={item.href} onClick={() => setSidebarOpen(false)} className={`flex items-center gap-3 rounded-lg px-3 py-2 text-sm font-medium transition-colors ${isActive ? 'bg-brand-50 text-brand-800 dark:bg-brand-950/60 dark:text-brand-300' : 'text-slate-600 hover:bg-stone-50 hover:text-brand-800 dark:text-slate-300 dark:hover:bg-slate-900 dark:hover:text-brand-300'}`}><item.icon className="h-5 w-5 flex-shrink-0" />{item.label}</Link>; })}</div></nav><div className="border-t border-stone-100 p-4 dark:border-slate-700"><div className="mb-3 flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-full bg-brand-100 text-sm font-semibold text-brand-800 dark:bg-brand-950 dark:text-brand-300">{user?.firstName?.[0]}{user?.lastName?.[0]}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium text-slate-900 dark:text-white">{user?.firstName} {user?.lastName}</p><p className="text-xs capitalize text-slate-500 dark:text-slate-400">{user?.role}</p></div></div><Link href="/dashboard/profile/settings" className="flex w-full items-center gap-2 rounded-lg px-3 py-2 text-sm text-slate-600 hover:bg-stone-50 hover:text-brand-800 dark:text-slate-300 dark:hover:bg-slate-900"><Cog6ToothIcon className="h-4 w-4" />Settings</Link><button onClick={handleLogout} className="flex w-full items-center gap-2 rounded-lg px-3 py-2 text-sm text-red-600 hover:bg-red-50 dark:hover:bg-red-950/30"><ArrowLeftStartOnRectangleIcon className="h-4 w-4" />Logout</button></div></div></aside>
    <main className="min-h-screen pt-14 lg:ml-64"><div className="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8">{children}</div></main>
  </div>;
}
