'use client';
import { useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import Link from 'next/link';
import { BookOpenIcon, PlayIcon, ClockIcon, ArrowLeftIcon, ChevronRight, Loader2 } from 'lucide-react';
import { useAuth } from '@/contexts/AuthContext';
import { fetchCourseByIdOrSlug, enrollInCourse } from '@/services/api/courseService';
import { getSupabase } from '@/lib/supabase';

export default function CourseDetailPage(){
 const params=useParams(); const {token}=useAuth(); const courseRef=String(params?.courseId||'');
 const [course,setCourse]=useState<any>(null); const [topics,setTopics]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [enrolled,setEnrolled]=useState(false); const [enrolling,setEnrolling]=useState(false);
 useEffect(()=>{if(!courseRef)return;let cancelled=false;(async()=>{setLoading(true);setError('');try{const res=await fetchCourseByIdOrSlug(courseRef,token??undefined);if(cancelled)return;const loaded=res.course||null;setCourse(loaded);if(loaded?.lessons?.length){const ids=Array.from(new Set(loaded.lessons.map((l:any)=>l.topic_id).filter(Boolean)));if(ids.length){const {data,error:e}=await getSupabase().from('topics').select('id,name,description,order_index').in('id',ids).order('order_index');if(e)console.warn('Topic lookup failed; lessons will still be shown:',e.message);if(!cancelled)setTopics(data||[]);}}}catch(e:any){if(!cancelled)setError(e?.message||'Unable to load course')}finally{if(!cancelled)setLoading(false)}})();return()=>{cancelled=true}},[courseRef,token]);
 const handleEnroll=async()=>{if(!token||!course?.id)return;setEnrolling(true);try{await enrollInCourse(course.id,token);setEnrolled(true)}catch(e:any){alert(e?.message||'Failed to enroll')}finally{setEnrolling(false)}};
 if(loading)return <div className="flex min-h-[60vh] items-center justify-center"><Loader2 className="h-8 w-8 animate-spin text-[#151A3A]"/></div>;
 if(error||!course)return <div className="py-16 text-center"><BookOpenIcon className="mx-auto mb-4 h-12 w-12 text-stone-300"/><h2 className="mb-2 text-xl font-semibold text-[#151A3A]">Course not found</h2><p className="mb-4 text-sm text-red-600">{error}</p><Link href="/dashboard/lessons" className="font-semibold text-[#151A3A]">Back to curriculum</Link></div>;
 const courseRoute=course.slug||course.id;const lessons=course.lessons||[];const topicMap=new Map(topics.map((t:any)=>[t.id,t]));const byTopic=new Map<string,{topic:any,lessons:any[]}>();
 lessons.forEach((lesson:any)=>{const topic=topicMap.get(lesson.topic_id);const key=topic?.id||lesson.section_id||'unassigned';if(!byTopic.has(key))byTopic.set(key,{topic:topic||null,lessons:[]});byTopic.get(key)!.lessons.push(lesson)});
 const topicGroups=Array.from(byTopic.values()).sort((a,b)=>(a.topic?.order_index??999)-(b.topic?.order_index??999));
 const lessonHref=(lesson:any)=>`/dashboard/lessons/${encodeURIComponent(courseRoute)}/${encodeURIComponent(lesson.slug||lesson.id)}`;
 return <div className="space-y-6"><Link href="/dashboard/lessons" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-500"><ArrowLeftIcon className="h-4 w-4"/>Back to curriculum</Link><div className="rounded-3xl bg-[#151A3A] p-7 text-white shadow-xl"><div className="flex flex-col gap-5 md:flex-row md:items-start md:justify-between"><div><span className="inline-block rounded-full bg-white/10 px-3 py-1 text-sm font-medium">{course.difficulty||'Core course'}</span><h1 className="mt-3 text-3xl font-extrabold">{course.title}</h1><p className="mt-2 max-w-2xl text-slate-300">{course.shortDescription||course.description||'Learn this subject through structured teaching, examples and practice.'}</p></div><button onClick={handleEnroll} disabled={enrolling||enrolled} className={`rounded-xl px-6 py-3 font-semibold ${enrolled?'bg-emerald-500 text-white':'bg-white text-[#151A3A]'} disabled:opacity-50`}>{enrolled?'✓ Enrolled':enrolling?'Enrolling...':course.isFree?'Start free':'Enroll'}</button></div><div className="mt-5 flex gap-6 text-sm text-slate-300"><span className="flex items-center gap-1"><ClockIcon className="h-4 w-4"/>{course.totalDurationHours||0}h content</span><span className="flex items-center gap-1"><BookOpenIcon className="h-4 w-4"/>{lessons.length} lessons</span></div></div>
 <div className="rounded-2xl border border-stone-200 bg-white p-6 shadow-sm dark:border-slate-700 dark:bg-[#1b2045]"><h2 className="mb-2 text-xl font-extrabold text-[#151A3A] dark:text-white">Topics & Lessons</h2><p className="mb-5 text-sm text-slate-500">Work through each topic, then open the lesson to learn, practise and track completion.</p>{!lessons.length?<div className="rounded-xl border border-dashed border-stone-300 p-10 text-center text-slate-500">This course has no published lessons yet.</div>:topicGroups.map((group:any,i:number)=><section key={group.topic?.id||group.lessons[0]?.section_id||'unassigned'} className="mb-4 overflow-hidden rounded-xl border border-stone-200 dark:border-slate-700"><div className="flex items-center gap-3 bg-stone-50 px-4 py-3 dark:bg-[#151A3A]"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-[#151A3A] text-xs font-bold text-white">{i+1}</span><div><div className="font-bold text-[#151A3A] dark:text-white">{group.topic?.name||'Topic'}</div>{group.topic?.description&&<div className="text-xs text-slate-500">{group.topic.description}</div>}</div></div><div className="divide-y divide-stone-100 dark:divide-slate-700">{group.lessons.map((lesson:any)=><Link key={lesson.id} href={lessonHref(lesson)} className="flex items-center gap-3 px-4 py-4 transition hover:bg-stone-50 dark:hover:bg-[#151A3A]"><PlayIcon className="h-4 w-4 shrink-0 text-[#151A3A] dark:text-slate-300"/><span className="flex-1 text-sm font-medium text-slate-700 dark:text-slate-200">{lesson.title}</span><span className="text-xs text-slate-400">{lesson.estimatedMinutes||10} min</span><ChevronRight className="h-4 w-4 text-slate-300"/></Link>)}</div></section>)}</div></div>;
}
