export interface TableDefinition {
  name: string;
  module: string;
  phase: 'foundation' | 'core' | 'assessment' | 'monetization' | 'ai' | 'ecosystem';
}

export const TABLE_DEFINITIONS: TableDefinition[] = [
  { name: 'users', module: 'auth', phase: 'foundation' },
  { name: 'roles', module: 'auth', phase: 'foundation' },
  { name: 'user_roles', module: 'auth', phase: 'foundation' },
  { name: 'sessions', module: 'auth', phase: 'foundation' },
  { name: 'password_resets', module: 'auth', phase: 'foundation' },
  { name: 'education_systems', module: 'education', phase: 'foundation' },
  { name: 'education_levels', module: 'education', phase: 'foundation' },
  { name: 'programs', module: 'education', phase: 'foundation' },
  { name: 'classes', module: 'education', phase: 'foundation' },
  { name: 'terms', module: 'education', phase: 'foundation' },
  { name: 'subjects', module: 'curriculum', phase: 'foundation' },
  { name: 'topics', module: 'curriculum', phase: 'foundation' },
  { name: 'subtopics', module: 'curriculum', phase: 'foundation' },
  { name: 'courses', module: 'courses', phase: 'core' },
  { name: 'course_sections', module: 'courses', phase: 'core' },
  { name: 'lessons', module: 'lessons', phase: 'core' },
  { name: 'lesson_resources', module: 'lessons', phase: 'core' },
  { name: 'student_courses', module: 'progress', phase: 'core' },
  { name: 'lesson_progress', module: 'progress', phase: 'core' },
  { name: 'study_sessions', module: 'progress', phase: 'core' },
  { name: 'questions', module: 'questions', phase: 'assessment' },
  { name: 'quizzes', module: 'assessments', phase: 'assessment' },
  { name: 'quiz_questions', module: 'assessments', phase: 'assessment' },
  { name: 'exams', module: 'exams', phase: 'assessment' },
  { name: 'exam_questions', module: 'exams', phase: 'assessment' },
  { name: 'exam_attempts', module: 'exams', phase: 'assessment' },
  { name: 'exam_answers', module: 'exams', phase: 'assessment' },
  { name: 'assignments', module: 'assignments', phase: 'assessment' },
  { name: 'submissions', module: 'assignments', phase: 'assessment' },
  { name: 'teachers', module: 'teachers', phase: 'ecosystem' },
  { name: 'parents', module: 'parents', phase: 'ecosystem' },
  { name: 'parent_children', module: 'parents', phase: 'ecosystem' },
  { name: 'schools', module: 'schools', phase: 'ecosystem' },
  { name: 'school_students', module: 'schools', phase: 'ecosystem' },
  { name: 'school_teachers', module: 'schools', phase: 'ecosystem' },
  { name: 'school_classes', module: 'schools', phase: 'ecosystem' },
  { name: 'subscription_plans', module: 'subscriptions', phase: 'monetization' },
  { name: 'subscriptions', module: 'subscriptions', phase: 'monetization' },
  { name: 'payments', module: 'payments', phase: 'monetization' },
  { name: 'transactions', module: 'payments', phase: 'monetization' },
  { name: 'invoices', module: 'payments', phase: 'monetization' },
  { name: 'notifications', module: 'notifications', phase: 'ecosystem' },
  { name: 'badges', module: 'gamification', phase: 'ecosystem' },
  { name: 'achievements', module: 'gamification', phase: 'ecosystem' },
  { name: 'student_points', module: 'gamification', phase: 'ecosystem' },
  { name: 'leaderboards', module: 'gamification', phase: 'ecosystem' },
  { name: 'ai_conversations', module: 'ai', phase: 'ai' },
  { name: 'ai_messages', module: 'ai', phase: 'ai' },
  { name: 'ai_usage', module: 'ai', phase: 'ai' },
  { name: 'flashcards', module: 'flashcards', phase: 'ecosystem' },
  { name: 'flashcard_reviews', module: 'flashcards', phase: 'ecosystem' },
  { name: 'library_resources', module: 'library', phase: 'core' },
  { name: 'community_posts', module: 'community', phase: 'ecosystem' },
  { name: 'comments', module: 'community', phase: 'ecosystem' },
  { name: 'reports', module: 'reports', phase: 'ecosystem' },
  { name: 'audit_logs', module: 'administration', phase: 'ecosystem' },
];
