'use client';

import Link from 'next/link';
import { GraduationCap, Sparkles, BookOpen } from 'lucide-react';

const classes=[
 ['primary-1','Primary 1','Foundation learning across core subjects','📚'],['primary-2','Primary 2','Build confidence and core skills','📘'],['primary-3','Primary 3','Learn, practise and strengthen concepts','✏️'],['primary-4','Primary 4','Develop deeper understanding','🧠'],['primary-5','Primary 5','Master key primary concepts','🎯'],['primary-6','Primary 6','Complete the primary learning journey','🏆'],
 ['jss-1','JSS 1','Begin junior secondary learning','🎓'],['jss-2','JSS 2','Build stronger secondary knowledge','📖'],['jss-3','JSS 3','Prepare for senior secondary school','🚀'],
 ['ss-1','SS 1','Build a strong senior secondary foundation','🔬'],['ss-2','SS 2','Deepen concepts and examination skills','📐'],['ss-3','SS 3','Complete senior secondary preparation','🏅']
] as const;

export default function CoursesPage(){return <div className="space-y-8"><section className="overflow-hidden rounded-3xl bg-[#151A3A] p-7 text-white shadow-xl sm:p-10"><div className="flex items-end justify-between gap-6"><div><div className="mb-3 inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1.5 text-xs font-bold"><Sparkles className="h-4 w-4"/>THE GUIDE COURSES</div><h1 className="text-3xl font-extrabold tracking-tight sm:text-5xl">Choose your class</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-300 sm:text-base">Courses are organised around the Nigerian education system. Choose your class first, then see only the subjects and courses that belong to that class.</p></div><GraduationCap className="hidden h-16 w-16 text-white/60 md:block"/></div></section><Section title="Primary School" range="Primary 1–6" items={classes.slice(0,6)}/><Section title="Junior Secondary" range="JSS 1–3" items={classes.slice(6,9)}/><Section title="Senior Secondary" range="SS 1–3" items={classes.slice(9)}/><div className="rounded-2xl border border-stone-200 bg-white p-5 text-sm text-slate-600 dark:border-slate-700 dark:bg-[#1b2045] dark:text-slate-300"><BookOpen className="mb-2 h-5 w-5 text-[#151A3A] dark:text-white"/><strong className="text-[#151A3A] dark:text-white">Course structure:</strong> class → subject → term/course → topics → teaching → practice questions.</div></div>}
function Section({title,range,items}:{title:string;range:string;items:readonly (readonly [string,string,string,string])[]}){return <section><div className="mb-5"><h2 className="text-2xl font-extrabold text-[#151A3A] dark:text-white">{title}</h2><p className="mt-1 text-sm text-slate-500">{range}</p></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{items.map(([slug,name,desc,icon])=><Link key={slug} href={`/dashboard/lessons/class/${slug}`} className="group rounded-2xl border border-stone-200 bg-white p-5 shadow-sm transition hover:-translate-y-1 hover:border-[#151A3A]/30 hover:shadow-lg dark:border-slate-700 dark:bg-[#1b2045]"><div className="flex items-center justify-between"><span className="text-3xl">{icon}</span><span className="rounded-full bg-[#151A3A] px-3 py-1 text-xs font-bold text-white">Open class</span></div><h3 className="mt-5 text-xl font-extrabold text-[#151A3A] dark:text-white">{name}</h3><p className="mt-2 text-sm leading-6 text-slate-500 dark:text-slate-400">{desc}</p><div className="mt-5 text-sm font-bold text-[#151A3A] dark:text-white">See courses by subject →</div></Link>)}</div></section>}
