export * as CommonSchemas from './common';
export * from './user';
export * from './education';
export * from './curriculum';
export * from './course';
export * from './lesson';
export * from './question';
export * from './assessment';
export * from './exam';
export * from './assignment';
export * from './progress';
export * from './school';
export * from './ai';
export * from './community';
export * from './flashcard';
export * from './gamification';
export * from './library';
export * from './notification';
export * from './person';
export * as PaymentSchemas from './payment';
export * as SubscriptionSchemas from './subscription';
