import Link from 'next/link';

const features = [
  { title: 'Structured Courses', description: 'Curriculum-aligned courses from primary school through university level.', icon: '📚' },
  { title: 'AI Tutor', description: 'Get personalized help from an AI-powered tutor available 24/7.', icon: '✦' },
  { title: 'Past Questions', description: 'Practice with WAEC, NECO, JAMB, and NABTEB past questions.', icon: '✓' },
  { title: 'Exams & Quizzes', description: 'Test your knowledge with timed exams and instant feedback.', icon: '⌁' },
  { title: 'Flashcards', description: 'Memorize key concepts with spaced repetition flashcards.', icon: '▣' },
  { title: 'Track Progress', description: 'Monitor your learning journey with detailed analytics and reports.', icon: '↗' },
];

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-stone-50 text-slate-900 dark:bg-[#151A3A] dark:text-slate-100">
      <nav className="sticky top-0 z-50 border-b border-stone-200/80 bg-white/95 backdrop-blur-sm dark:border-slate-700/80 dark:bg-[#151A3A]/95">
        <div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-4 sm:px-6 lg:px-8">
          <Link href="/" aria-label="THE GUIDE home" className="flex items-center"><img src="/logos/primary-logo.jfif" alt="THE GUIDE" className="h-14 w-auto max-w-[220px] object-contain sm:h-16" /></Link>
          <div className="flex items-center gap-2 sm:gap-3"><Link href="/login" className="rounded-lg px-3 py-2 text-sm font-medium text-slate-600 hover:text-brand-700 dark:text-slate-300 dark:hover:text-brand-300">Log in</Link><Link href="/register" className="rounded-lg bg-[#151A3A] px-4 py-2 text-sm font-semibold text-white shadow-brand-sm hover:bg-[#202750]">Sign up</Link></div>
        </div>
      </nav>
      <section className="relative overflow-hidden"><div className="mx-auto max-w-7xl px-4 py-20 sm:px-6 sm:py-28 lg:px-8"><div className="mx-auto max-w-3xl text-center"><img src="/logos/primary-logo.jfif" alt="THE GUIDE" className="mx-auto mb-7 h-32 w-auto max-w-[360px] object-contain drop-shadow-xl sm:h-40" /><p className="text-sm font-semibold uppercase tracking-[0.2em] text-brand-700 dark:text-brand-300">Learn. Practice. Master.</p><h1 className="mt-3 text-4xl font-extrabold tracking-tight text-[#151A3A] dark:text-white sm:text-5xl lg:text-6xl">Your Path to <span className="text-brand-600 dark:text-brand-300">Smarter Learning</span></h1><p className="mx-auto mt-6 max-w-2xl text-lg text-slate-600 dark:text-slate-300 sm:text-xl">A comprehensive Nigerian educational platform covering primary school through university. Courses, AI tutoring, past questions, and more.</p><div className="mt-10 flex flex-col items-center justify-center gap-4 sm:flex-row"><Link href="/register" className="w-full rounded-xl bg-[#151A3A] px-8 py-3.5 text-center font-semibold text-white shadow-brand hover:bg-[#202750] sm:w-auto">Get Started Free</Link><Link href="/login" className="w-full rounded-xl border border-stone-300 bg-white px-8 py-3.5 text-center font-semibold text-slate-700 hover:border-brand-300 hover:bg-brand-50 hover:text-brand-800 dark:border-slate-600 dark:bg-slate-900 dark:text-slate-200 dark:hover:bg-slate-800 sm:w-auto">I have an account</Link></div></div></div></section>
      <section className="border-t border-stone-200 bg-white py-16 dark:border-slate-700 dark:bg-[#1b2045] sm:py-24"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mb-12 text-center"><h2 className="text-3xl font-bold text-[#151A3A] dark:text-white">Everything you need to succeed</h2><p className="mt-3 text-lg text-slate-600 dark:text-slate-300">Built for Nigerian students at every level</p></div><div className="grid grid-cols-1 gap-8 sm:grid-cols-2 lg:grid-cols-3">{features.map((feature)=><div key={feature.title} className="rounded-2xl border border-stone-200 bg-white p-6 shadow-sm transition-all hover:-translate-y-0.5 hover:border-brand-300 hover:shadow-brand-sm dark:border-slate-700 dark:bg-[#151A3A]"><div className="mb-4 flex h-11 w-11 items-center justify-center rounded-xl bg-brand-50 text-xl text-brand-700 dark:bg-brand-950/60 dark:text-brand-300">{feature.icon}</div><h3 className="mb-2 font-semibold text-[#151A3A] dark:text-white">{feature.title}</h3><p className="text-sm leading-relaxed text-slate-600 dark:text-slate-300">{feature.description}</p></div>)}</div></div></section>
      <section className="py-16 sm:py-24"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="brand-gradient brand-glow rounded-2xl px-8 py-12 text-center sm:px-16 sm:py-16"><img src="/logos/primary-logo.jfif" alt="THE GUIDE" className="mx-auto mb-6 h-20 w-auto max-w-[220px] rounded-lg object-contain drop-shadow-lg" /><h2 className="text-3xl font-bold text-white">Ready to start learning?</h2><p className="mt-3 text-lg text-stone-200">Build knowledge, confidence, and results with THE GUIDE.</p><Link href="/register" className="mt-8 inline-block rounded-xl bg-white px-8 py-3.5 font-semibold text-[#151A3A] hover:bg-brand-50">Create your account</Link></div></div></section>
      <footer className="border-t border-stone-200 bg-white dark:border-slate-700 dark:bg-[#151A3A]"><div className="mx-auto flex max-w-7xl flex-col items-center justify-between gap-4 px-4 py-8 sm:flex-row sm:px-6 lg:px-8"><Link href="/" aria-label="THE GUIDE home"><img src="/logos/primary-logo.jfif" alt="THE GUIDE" className="h-12 w-auto max-w-[180px] object-contain" /></Link><p className="text-sm text-slate-500 dark:text-slate-400">© {new Date().getFullYear()} THE GUIDE. All rights reserved.</p></div></footer>
    </div>
  );
}
