'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import Link from 'next/link';
import { CheckCircle2, ChevronLeft, ChevronRight, Clock3, Download, Loader2, Sparkles } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import { getSupabase } from '@/lib/supabase';
import { sendAiTutorMessage } from '@/services/api/aiService';
import { apiConfig, getAuthHeaders, handleApiResponse } from '@/services/api/config';
import { useAuth } from '@/contexts/AuthContext';

type Tab = 'learn' | 'practice' | 'video' | 'resources';
type Question = {
  id:string;
  question_text:string;
  options:any;
  difficulty?:string|null;
  marks?:number|null;
  question_image_url?:string|null;
  generated?:boolean;
  correct_answer?:any;
  explanation?:string|null;
};
type CheckResult={isCorrect:boolean;correctAnswer:unknown;explanation:string|null;explanationImageUrl?:string|null};

function isUuid(value:string){return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value)}
function optionsOf(v:any){return Array.isArray(v)?v.map((x:any,i:number)=>({id:String(x?.id??x?.label??String.fromCharCode(65+i)),text:String(x?.text??x?.value??x)})):v&&typeof v==='object'?Object.entries(v).map(([id,x]:any)=>({id,text:String(x?.text??x?.value??x)})):[]}
function answerOf(v:any){return typeof v==='string'||typeof v==='number'||typeof v==='boolean'?String(v):v&&typeof v==='object'?String(v.id??v.label??v.answer??v.value??''):''}

function LessonContent({content}:{content:string}){
 const safe=String(content||'').trim();
 if(!safe)return <div className="rounded-2xl border border-dashed border-stone-300 p-8 text-slate-500">No written lesson content is available yet.</div>;
 return <article className="lesson-prose text-[16px] leading-8 text-slate-700 dark:text-slate-200"><ReactMarkdown components={{
   h1:({children})=><h2 className="mb-5 mt-2 text-3xl font-extrabold tracking-tight text-[#151A3A] dark:text-white">{children}</h2>,
   h2:({children})=><h3 className="mb-4 mt-10 text-2xl font-extrabold text-[#151A3A] dark:text-white">{children}</h3>,
   h3:({children})=><h4 className="mb-3 mt-8 text-xl font-extrabold text-[#151A3A] dark:text-white">{children}</h4>,
   p:({children})=><p className="mb-5">{children}</p>,ul:({children})=><ul className="mb-6 ml-6 list-disc space-y-2">{children}</ul>,ol:({children})=><ol className="mb-6 ml-6 list-decimal space-y-2">{children}</ol>,li:({children})=><li className="pl-1">{children}</li>,strong:({children})=><strong className="font-extrabold text-slate-900 dark:text-white">{children}</strong>,blockquote:({children})=><blockquote className="my-6 border-l-4 border-[#151A3A] bg-stone-50 px-5 py-3 italic dark:bg-[#151A3A]">{children}</blockquote>,code:({children,className})=>className?.includes('language-')?<code className="block overflow-x-auto rounded-xl bg-slate-950 p-5 font-mono text-sm leading-6 text-white">{children}</code>:<code className="rounded bg-stone-100 px-1.5 py-0.5 font-mono text-[.9em] dark:bg-slate-800">{children}</code>,pre:({children})=><pre className="my-6 overflow-x-auto rounded-xl">{children}</pre>,
 }}>{safe}</ReactMarkdown></article>
}

export default function LessonPage(){
 const params=useParams();const router=useRouter();const {token}=useAuth();const courseRef=String(params?.courseId||'');const lessonRef=String(params?.lessonId||'');
 const [lesson,setLesson]=useState<any>(null);const [course,setCourse]=useState<any>(null);const [lessons,setLessons]=useState<any[]>([]);const [questions,setQuestions]=useState<Question[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [completed,setCompleted]=useState(false);const [completing,setCompleting]=useState(false);const [teaching,setTeaching]=useState(false);const [teacherText,setTeacherText]=useState('');const [activeTab,setActiveTab]=useState<Tab>('learn');const [qi,setQi]=useState(0);const [selected,setSelected]=useState<string|null>(null);const [checked,setChecked]=useState<CheckResult|null>(null);const [checking,setChecking]=useState(false);const [score,setScore]=useState(0);const [attempted,setAttempted]=useState(0);const [practiceLoading,setPracticeLoading]=useState(false);const videoRef=useRef<HTMLVideoElement>(null);

 useEffect(()=>{let cancelled=false;(async()=>{if(!courseRef||!lessonRef)return;setLoading(true);setError('');try{const s=getSupabase();let cq=s.from('courses').select('id,title,slug,short_description,subject_id,class_id,term_id,status').limit(1);cq=isUuid(courseRef)?cq.eq('id',courseRef):cq.eq('slug',courseRef);const {data:c,error:ce}=await cq.maybeSingle();if(ce)throw ce;if(!c)throw new Error('Course not found');const {data:ls,error:le}=await s.from('lessons').select('id,course_id,topic_id,slug,title,description,written_content,learning_objectives,key_points,estimated_minutes,video_url,video_duration_seconds,content_type,is_free,is_published,order_index').eq('course_id',c.id).eq('is_published',true).order('order_index',{ascending:true});if(le)throw le;const list=ls||[];const found=list.find((l:any)=>l.id===lessonRef||l.slug===lessonRef);if(!found)throw new Error('Lesson not found');let q:Question[]=[];if(found.topic_id&&c.class_id&&c.subject_id){const response=await fetch(`${apiConfig.baseUrl}/questions?topicId=${encodeURIComponent(found.topic_id)}&classId=${encodeURIComponent(c.class_id)}&subjectId=${encodeURIComponent(c.subject_id)}&limit=20`,{credentials:apiConfig.credentials});const payload=await handleApiResponse<any>(response);q=(payload?.data?.questions||[]).map((x:any)=>({id:x.id,question_text:x.questionText,options:x.options,difficulty:x.difficulty,marks:x.marks,question_image_url:x.questionImageUrl,generated:false}));}
 if(!cancelled){setCourse(c);setLessons(list);setLesson(found);setQuestions(q);setQi(0);setSelected(null);setChecked(null);setScore(0);setAttempted(0)}}catch(e:any){if(!cancelled)setError(e?.message||'Unable to load lesson')}finally{if(!cancelled)setLoading(false)}})();return()=>{cancelled=true}},[courseRef,lessonRef]);

 const lessonIndex=useMemo(()=>lessons.findIndex(l=>l.id===lesson?.id),[lessons,lesson?.id]);const previous=lessons[lessonIndex-1];const next=lessons[lessonIndex+1];const currentQ=questions[qi];
 useEffect(()=>{if(!lesson||!token)return;let cancelled=false;(async()=>{setTeaching(true);setTeacherText('');try{const response=await sendAiTutorMessage({message:`Teach this lesson as an accurate Nigerian curriculum-aligned teacher. Lesson title: ${lesson.title}. Course: ${course?.title||'Unknown'}. Existing notes: ${lesson.written_content||lesson.description||'none'}. Learning objectives: ${(lesson.learning_objectives||[]).join('; ')||'none'}. Give a clear explanation, definitions, step-by-step teaching, accurate worked examples where appropriate, common misconceptions and a short recap. Do not invent syllabus claims.`,context:{lessonId:lesson.id,courseId:lesson.course_id,lessonTitle:lesson.title}},token);if(!cancelled)setTeacherText(response.message?.content||'')}catch{if(!cancelled)setTeacherText('')}finally{if(!cancelled)setTeaching(false)}})();return()=>{cancelled=true}},[lesson?.id,token,course?.title]);

 const generatePractice=async()=>{if(!lesson||!token||practiceLoading)return;setPracticeLoading(true);setError('');try{const response=await sendAiTutorMessage({message:`Create 5 Nigerian curriculum-aligned multiple-choice practice questions for this lesson. Lesson: ${lesson.title}. Course: ${course?.title||''}. Notes: ${lesson.written_content||''}. Return ONLY valid JSON array. Each item must have question_text, options as an object with A,B,C,D, correct_answer as A/B/C/D, and explanation. Make every question answerable from the lesson and avoid invented facts.`,context:{lessonId:lesson.id,courseId:lesson.course_id,mode:'practice-generation'}},token);const raw=response.message?.content||'';const match=raw.match(/\[[\s\S]*\]/);if(!match)throw new Error('AI did not return a valid practice set');const parsed=JSON.parse(match[0]);setQuestions(parsed.map((x:any,i:number)=>({...x,id:`generated-${i}`,generated:true})));setQi(0);setSelected(null);setChecked(null);setScore(0);setAttempted(0);setActiveTab('practice')}catch(e:any){setError(e?.message||'Unable to generate practice')}finally{setPracticeLoading(false)}};
 const opts=optionsOf(currentQ?.options);const correct=answerOf(checked?.correctAnswer??currentQ?.correct_answer);
 const selectAnswer=async(id:string)=>{if(selected||!currentQ||checking)return;setSelected(id);setChecking(true);setError('');try{if(currentQ.generated){const ok=id===answerOf(currentQ.correct_answer);setChecked({isCorrect:ok,correctAnswer:currentQ.correct_answer,explanation:currentQ.explanation||null});setScore(x=>x+(ok?1:0));setAttempted(x=>x+1);return}if(!token)throw new Error('Sign in to check your answer');const response=await fetch(`${apiConfig.baseUrl}/questions/${currentQ.id}/check`,{method:'POST',headers:getAuthHeaders(token),credentials:apiConfig.credentials,body:JSON.stringify({answer:id})});const payload=await handleApiResponse<{data:{result:CheckResult}}>(response);setChecked(payload.data.result);setScore(x=>x+(payload.data.result.isCorrect?1:0));setAttempted(x=>x+1)}catch(e:any){setSelected(null);setError(e?.message||'Unable to check answer')}finally{setChecking(false)}};
 const nextQuestion=()=>{setQi(x=>Math.min(x+1,questions.length-1));setSelected(null);setChecked(null)};
 const previousQuestion=()=>{setQi(x=>Math.max(x-1,0));setSelected(null);setChecked(null)};
 const markComplete=async()=>{if(!lesson||completed||completing||!token)return;setCompleting(true);setError('');try{const response=await fetch(`${apiConfig.baseUrl}/lessons/${lesson.id}/complete`,{method:'POST',headers:getAuthHeaders(token),credentials:apiConfig.credentials});await handleApiResponse(response);setCompleted(true)}catch(e:any){setError(e?.message||'Unable to mark lesson complete')}finally{setCompleting(false)}};
 const goTo=(target?:any)=>{if(target)router.push(`/dashboard/lessons/${encodeURIComponent(course?.slug||course?.id)}/${encodeURIComponent(target.slug||target.id)}`)};
 if(loading)return <div className="flex min-h-[60vh] items-center justify-center"><Loader2 className="h-8 w-8 animate-spin text-[#151A3A]"/></div>;
 if(error&&!lesson)return <div className="mx-auto max-w-2xl py-16 text-center"><h1 className="text-xl font-bold text-[#151A3A]">Unable to open lesson</h1><p className="mt-2 text-slate-500">{error}</p><Link href="/dashboard/lessons" className="mt-6 inline-flex rounded-xl bg-[#151A3A] px-5 py-2.5 font-semibold text-white">Back to lessons</Link></div>;
 if(!lesson||!course)return null;
 const notes=lesson.written_content||lesson.description||'';
 const resources=Array.isArray(lesson.resources)?lesson.resources:[];
 return <div className="mx-auto max-w-6xl space-y-6">
 <div className="flex items-center gap-2 text-sm text-slate-500"><Link href="/dashboard/lessons">Lessons</Link><ChevronRight className="h-4 w-4"/><Link href={`/dashboard/courses/${encodeURIComponent(course.slug||course.id)}`} className="truncate">{course.title}</Link><ChevronRight className="h-4 w-4"/><span className="truncate text-slate-900 dark:text-white">{lesson.title}</span></div>
 {error&&<div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
 <header className="rounded-3xl bg-[#151A3A] p-6 text-white shadow-xl sm:p-8"><p className="text-xs font-bold uppercase tracking-[0.16em] text-slate-300">{course.title}</p><h1 className="mt-2 text-3xl font-extrabold sm:text-4xl">{lesson.title}</h1><div className="mt-4 flex flex-wrap items-center gap-4 text-sm text-slate-300"><span className="inline-flex items-center gap-1"><Clock3 className="h-4 w-4"/>{lesson.estimated_minutes||10} min</span><span>{lessonIndex>=0?`Lesson ${lessonIndex+1} of ${lessons.length}`:''}</span></div></header>
 <div className="overflow-hidden rounded-2xl border border-stone-200 bg-white shadow-sm dark:border-slate-700 dark:bg-[#1b2045]"><nav className="flex overflow-x-auto border-b border-stone-200 dark:border-slate-700">{(['learn','practice','video','resources'] as Tab[]).map(tab=><button key={tab} onClick={()=>setActiveTab(tab)} className={`min-w-[120px] flex-1 px-4 py-3 text-sm font-bold ${activeTab===tab?'border-b-2 border-[#151A3A] text-[#151A3A] dark:text-white':'text-slate-500'}`}>{tab==='learn'?'Learn & Teach':tab==='practice'?`Practice${questions.length?` (${questions.length})`:''}`:tab==='video'?'Video':'Resources'}</button>)}</nav>
 {activeTab==='learn'&&<div className="grid gap-8 p-6 lg:grid-cols-[1fr_300px] sm:p-8"><main><section><h2 className="text-2xl font-extrabold text-[#151A3A] dark:text-white">What you will learn</h2><ul className="mt-4 space-y-3">{(lesson.learning_objectives?.length?lesson.learning_objectives:[`Understand ${lesson.title}`,`Apply the ideas in ${lesson.title}`,`Check your understanding`]).map((x:any,i:number)=><li key={i} className="flex gap-3 text-slate-600 dark:text-slate-300"><CheckCircle2 className="mt-1 h-5 w-5 shrink-0 text-emerald-600"/>{x}</li>)}</ul></section><section className="mt-10"><h2 className="text-2xl font-extrabold text-[#151A3A] dark:text-white">Lesson</h2><div className="mt-5"><LessonContent content={notes}/></div></section>{!!lesson.key_points?.length&&<section className="mt-10 rounded-2xl bg-stone-50 p-6 dark:bg-[#151A3A]"><h2 className="text-xl font-extrabold text-[#151A3A] dark:text-white">Key points</h2><ul className="mt-4 space-y-2 text-slate-700 dark:text-slate-200">{lesson.key_points.map((x:any,i:number)=><li key={i} className="flex gap-2"><span>•</span>{x}</li>)}</ul></section>}</main><aside className="h-fit rounded-2xl border border-stone-200 bg-stone-50 p-5 dark:border-slate-700 dark:bg-[#151A3A]"><div className="flex items-center gap-2 font-extrabold text-[#151A3A] dark:text-white"><Sparkles className="h-5 w-5"/>THE GUIDE Teacher</div>{teaching?<div className="mt-4 flex items-center gap-2 text-sm text-slate-500"><Loader2 className="h-4 w-4 animate-spin"/>Preparing an explanation…</div>:<div className="mt-4 whitespace-pre-wrap text-sm leading-6 text-slate-600 dark:text-slate-300">{teacherText||'Read the lesson, then use Practice to check your understanding.'}</div>}<button onClick={()=>setActiveTab('practice')} className="mt-5 w-full rounded-xl bg-[#151A3A] px-4 py-2.5 text-sm font-bold text-white">Go to practice</button></aside></div>}
 {activeTab==='practice'&&<div className="p-6 sm:p-8">{!questions.length?<div className="mx-auto max-w-xl rounded-2xl border border-dashed border-stone-300 p-10 text-center dark:border-slate-700"><h2 className="text-xl font-extrabold text-[#151A3A] dark:text-white">Practice this lesson</h2><p className="mt-2 text-sm leading-6 text-slate-500">There are no stored questions attached to this topic yet. You can generate a lesson-specific practice set from the teaching material.</p><button onClick={generatePractice} disabled={!token||practiceLoading} className="mt-5 rounded-xl bg-[#151A3A] px-5 py-3 text-sm font-bold text-white disabled:opacity-50">{practiceLoading?'Generating practice…':'Generate practice set'}</button></div>:<div className="mx-auto max-w-3xl"><div className="mb-4 flex items-center justify-between text-sm text-slate-500"><span>Question {qi+1} of {questions.length}</span><span className="font-semibold">Score {score}/{attempted}</span></div><div className="rounded-2xl bg-stone-50 p-5 dark:bg-[#151A3A]"><p className="font-semibold leading-7 text-slate-900 dark:text-white">{currentQ?.question_text}</p>{currentQ?.question_image_url&&<img src={currentQ.question_image_url} alt="Question" className="mt-4 max-h-72 rounded-xl object-contain"/>}</div><div className="mt-4 space-y-2">{opts.map(o=><button key={o.id} disabled={!!selected||checking} onClick={()=>void selectAnswer(o.id)} className={`w-full rounded-xl border px-4 py-3 text-left ${selected?(o.id===correct?'border-emerald-300 bg-emerald-50 text-emerald-800':o.id===selected?'border-red-300 bg-red-50 text-red-800':'border-stone-200 bg-stone-50 text-slate-500'):'border-stone-200 bg-white hover:border-brand-300 dark:border-slate-700 dark:bg-[#151A3A]'}`}><b className="mr-2">{o.id}.</b>{o.text}</button>)}</div>{checked?.explanation&&<div className="mt-4 rounded-xl border border-brand-200 bg-brand-50 p-4 text-sm dark:border-brand-900 dark:bg-brand-950/30"><b>Explanation</b><p className="mt-1">{checked.explanation}</p></div>}<div className="mt-5 flex justify-between"><button onClick={previousQuestion} disabled={qi===0} className="rounded-xl border px-4 py-2 disabled:opacity-40">Previous</button><button onClick={nextQuestion} disabled={qi===questions.length-1} className="rounded-xl bg-[#151A3A] px-4 py-2 font-semibold text-white disabled:opacity-40">Next</button></div><div className="mt-6 text-center"><button onClick={generatePractice} disabled={!token||practiceLoading} className="text-sm font-semibold text-brand-700">Generate a fresh AI practice set</button></div></div>}</div>}
 {activeTab==='video'&&<div className="p-6 sm:p-8">{lesson.video_url?<video ref={videoRef} controls src={lesson.video_url} className="aspect-video w-full rounded-2xl bg-black"/>:<div className="rounded-2xl border border-dashed p-10 text-center text-slate-500">No video is available for this lesson.</div>}</div>}
 {activeTab==='resources'&&<div className="p-6 sm:p-8">{resources.length?<div className="space-y-3">{resources.map((r:any)=><a key={r.id} href={r.file_url} target="_blank" rel="noreferrer" className="flex items-center justify-between rounded-xl border border-stone-200 p-4 hover:border-brand-300 dark:border-slate-700"><span><b className="block">{r.title}</b><span className="text-sm text-slate-500">{r.description||r.resource_type}</span></span><Download className="h-5 w-5"/></a>)}</div>:<div className="rounded-2xl border border-dashed p-10 text-center text-slate-500">No downloadable resources are attached to this lesson.</div>}</div>}
 </div>
 <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><button onClick={()=>goTo(previous)} disabled={!previous} className="inline-flex items-center justify-center gap-2 rounded-xl border px-4 py-3 font-semibold disabled:opacity-40"><ChevronLeft className="h-4 w-4"/>Previous lesson</button><button onClick={()=>void markComplete()} disabled={completed||completing||!token} className={`rounded-xl px-5 py-3 font-semibold text-white ${completed?'bg-emerald-600':'bg-[#151A3A]'} disabled:opacity-60`}>{completed?'Completed':completing?'Saving…':'Mark complete'}</button><button onClick={()=>goTo(next)} disabled={!next} className="inline-flex items-center justify-center gap-2 rounded-xl border px-4 py-3 font-semibold disabled:opacity-40">Next lesson<ChevronRight className="h-4 w-4"/></button></div>
 </div>;
}
