'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import Link from 'next/link';
import { CheckCircle2, ChevronLeft, ChevronRight, Clock3, Download, Loader2, Sparkles } from 'lucide-react';
import { getSupabase } from '@/lib/supabase';
import { sendAiTutorMessage } from '@/services/api/aiService';
import { useAuth } from '@/contexts/AuthContext';

type Tab = 'learn' | 'practice' | 'video' | 'resources';

type Question = { id:string; question_text:string; options:any; correct_answer:any; explanation?:string|null; difficulty?:string|null; marks?:number|null; question_image_url?:string|null };

function isUuid(value:string){return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value)}
function optionsOf(v:any){return Array.isArray(v)?v.map((x:any,i:number)=>({id:String(x?.id??x?.label??String.fromCharCode(65+i)),text:String(x?.text??x?.value??x)})):v&&typeof v==='object'?Object.entries(v).map(([id,x]:any)=>({id,text:String(x?.text??x?.value??x)})):[]}
function answerOf(v:any){return typeof v==='string'||typeof v==='number'?String(v):v&&typeof v==='object'?String(v.id??v.label??v.answer??v.value??''):''}

function LessonContent({content}:{content:string}){
 const blocks=content.split(/\n{2,}/).map(x=>x.trim()).filter(Boolean);
 return <div className="space-y-6 text-[15px] leading-8 text-slate-700 dark:text-slate-200">{blocks.map((block,i)=>{const lines=block.split('\n').map(x=>x.trim()).filter(Boolean);const first=lines[0]||'';const heading=/^(#{1,6})\s+(.+)$/.exec(first);if(heading)return <section key={i}><h3 className="text-xl font-extrabold text-[#151A3A] dark:text-white">{heading[2]}</h3>{lines.slice(1).map((x,j)=><p key={j}>{x}</p>)}</section>;if(/^\*\*[^*]+\*\*$/.test(first))return <section key={i}><h3 className="text-lg font-extrabold text-[#151A3A] dark:text-white">{first.replace(/\*\*/g,'')}</h3>{lines.slice(1).map((x,j)=><p key={j}>{x}</p>)}</section>;return <section key={i}>{lines.map((x,j)=>/^[-•]\s/.test(x)?<li key={j} className="ml-5 list-disc">{x.replace(/^[-•]\s/,'')}</li>:<p key={j}>{x}</p>)}</section>})}</div>
}

export default function LessonPage(){
 const params=useParams();const router=useRouter();const {token}=useAuth();const courseRef=String(params?.courseId||'');const lessonRef=String(params?.lessonId||'');
 const [lesson,setLesson]=useState<any>(null);const [course,setCourse]=useState<any>(null);const [lessons,setLessons]=useState<any[]>([]);const [questions,setQuestions]=useState<Question[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [completed,setCompleted]=useState(false);const [teaching,setTeaching]=useState(false);const [teacherText,setTeacherText]=useState('');const [activeTab,setActiveTab]=useState<Tab>('learn');const [qi,setQi]=useState(0);const [selected,setSelected]=useState<string|null>(null);const [score,setScore]=useState(0);const [practiceLoading,setPracticeLoading]=useState(false);const videoRef=useRef<HTMLVideoElement>(null);

 useEffect(()=>{let cancelled=false;(async()=>{if(!courseRef||!lessonRef)return;setLoading(true);setError('');try{const s=getSupabase();let cq=s.from('courses').select('id,title,slug,short_description,subject_id,class_id,term_id').limit(1);cq=isUuid(courseRef)?cq.eq('id',courseRef):cq.eq('slug',courseRef);const {data:c,error:ce}=await cq.maybeSingle();if(ce)throw ce;if(!c)throw new Error('Course not found');const {data:ls,error:le}=await s.from('lessons').select('*').eq('course_id',c.id).eq('is_published',true).order('order_index',{ascending:true});if(le)throw le;const list=ls||[];const found=list.find((l:any)=>l.id===lessonRef||l.slug===lessonRef);if(!found)throw new Error('Lesson not found');let q:Question[]=[];if(found.topic_id&&c.class_id&&c.subject_id){const {data:qd,error:qe}=await s.from('questions').select('id,question_text,options,correct_answer,explanation,difficulty,marks,question_image_url').eq('topic_id',found.topic_id).eq('class_id',c.class_id).eq('subject_id',c.subject_id).eq('is_active',true).is('exam_name',null).limit(20);if(!qe)q=(qd||[]) as Question[];}
 if(!cancelled){setCourse(c);setLessons(list);setLesson(found);setQuestions(q);setQi(0);setSelected(null);setScore(0)}}catch(e:any){if(!cancelled)setError(e?.message||'Unable to load lesson')}finally{if(!cancelled)setLoading(false)}})();return()=>{cancelled=true}},[courseRef,lessonRef]);

 const lessonIndex=useMemo(()=>lessons.findIndex(l=>l.id===lesson?.id),[lessons,lesson?.id]);const previous=lessons[lessonIndex-1];const next=lessons[lessonIndex+1];const currentQ=questions[qi];
 useEffect(()=>{if(!lesson||!token)return;let cancelled=false;(async()=>{setTeaching(true);setTeacherText('');try{const response=await sendAiTutorMessage({message:`Teach this lesson as an accurate Nigerian curriculum-aligned teacher. Lesson title: ${lesson.title}. Course: ${course?.title||'Unknown'}. Existing notes: ${lesson.written_content||lesson.description||'none'}. Learning objectives: ${(lesson.learning_objectives||[]).join('; ')||'none'}. Give a clear explanation, definitions, step-by-step teaching, accurate worked examples where appropriate, common misconceptions and a short recap. Do not invent syllabus claims.`,context:{lessonId:lesson.id,courseId:lesson.course_id,lessonTitle:lesson.title}},token);if(!cancelled)setTeacherText(response.message?.content||'')}catch{if(!cancelled)setTeacherText('')}finally{if(!cancelled)setTeaching(false)}})();return()=>{cancelled=true}},[lesson?.id,token,course?.title]);

 const generatePractice=async()=>{if(!lesson||!token||practiceLoading)return;setPracticeLoading(true);try{const response=await sendAiTutorMessage({message:`Create 5 Nigerian secondary-school curriculum-aligned multiple-choice practice questions for this lesson. Lesson: ${lesson.title}. Course: ${course?.title||''}. Notes: ${lesson.written_content||''}. Return ONLY valid JSON array. Each item must have question_text, options as an object with A,B,C,D, correct_answer as A/B/C/D, and explanation. Make every question answerable from the lesson and avoid invented facts.`,context:{lessonId:lesson.id,courseId:lesson.course_id,mode:'practice-generation'}},token);const raw=response.message?.content||'';const match=raw.match(/\[[\s\S]*\]/);if(match){const parsed=JSON.parse(match[0]);setQuestions(parsed.map((x:any,i:number)=>({...x,id:`generated-${i}`})));setQi(0);setSelected(null);setScore(0);setActiveTab('practice')}}catch{}finally{setPracticeLoading(false)}};
 const opts=optionsOf(currentQ?.options);const correct=answerOf(currentQ?.correct_answer);const selectAnswer=(id:string)=>{if(selected)return;setSelected(id);if(id===correct)setScore(x=>x+1)};const nextQuestion=()=>{setQi(x=>Math.min(x+1,questions.length-1));setSelected(null)};
 const markComplete=async()=>{if(!lesson||completed)return;try{const s=getSupabase();const {data}=await s.auth.getUser();if(data.user){await s.from('lesson_progress').upsert({student_id:data.user.id,lesson_id:lesson.id,course_id:lesson.course_id,status:'completed',progress_percentage:100,completed_at:new Date().toISOString()},{onConflict:'student_id,lesson_id'})}}finally{setCompleted(true)}};
 const goTo=(target?:any)=>{if(target)router.push(`/dashboard/lessons/${encodeURIComponent(course?.slug||course?.id)}/${encodeURIComponent(target.slug||target.id)}`)};
 if(loading)return <div className="flex min-h-[60vh] items-center justify-center"><Loader2 className="h-8 w-8 animate-spin text-[#151A3A]"/></div>;
 if(error||!lesson||!course)return <div className="mx-auto max-w-2xl py-16 text-center"><h1 className="text-xl font-bold text-[#151A3A]">Unable to open lesson</h1><p className="mt-2 text-slate-500">{error||'Lesson not found'}</p><Link href="/dashboard/lessons" className="mt-6 inline-flex rounded-xl bg-[#151A3A] px-5 py-2.5 font-semibold text-white">Back to lessons</Link></div>;
 const notes=lesson.written_content||lesson.description||'No written notes have been added yet.';
 return <div className="mx-auto max-w-6xl space-y-6"><div className="flex items-center gap-2 text-sm text-slate-500"><Link href="/dashboard/lessons">Lessons</Link><ChevronRight className="h-4 w-4"/><Link href={`/dashboard/courses/${encodeURIComponent(course.slug||course.id)}`} className="truncate">{course.title}</Link><ChevronRight className="h-4 w-4"/><span className="truncate text-slate-900 dark:text-white">{lesson.title}</span></div>
 <header className="rounded-3xl bg-[#151A3A] p-6 text-white shadow-xl sm:p-8"><p className="text-xs font-bold uppercase tracking-[0.16em] text-slate-300">{course.title}</p><h1 className="mt-2 text-3xl font-extrabold sm:text-4xl">{lesson.title}</h1><div className="mt-4 flex flex-wrap items-center gap-4 text-sm text-slate-300"><span className="inline-flex items-center gap-1"><Clock3 className="h-4 w-4"/>{lesson.estimated_minutes||10} min</span><span>{lessonIndex>=0?`Lesson ${lessonIndex+1} of ${lessons.length}`:''}</span></div></header>
 <div className="overflow-hidden rounded-2xl border border-stone-200 bg-white shadow-sm dark:border-slate-700 dark:bg-[#1b2045]"><nav className="flex overflow-x-auto border-b border-stone-200 dark:border-slate-700">{(['learn','practice','video','resources'] as Tab[]).map(tab=><button key={tab} onClick={()=>setActiveTab(tab)} className={`min-w-[120px] flex-1 px-4 py-3 text-sm font-bold ${activeTab===tab?'border-b-2 border-[#151A3A] text-[#151A3A] dark:text-white':'text-slate-500'}`}>{tab==='learn'?'Learn & Teach':tab==='practice'?`Practice${questions.length?` (${questions.length})`:''}`:tab==='video'?'Video':'Resources'}</button>)}</nav>
 {activeTab==='learn'&&<div className="grid gap-8 p-6 lg:grid-cols-[1fr_300px] sm:p-8"><main><section><h2 className="text-2xl font-extrabold text-[#151A3A] dark:text-white">What you will learn</h2><ul className="mt-4 space-y-3">{(lesson.learning_objectives?.length?lesson.learning_objectives:[`Understand ${lesson.title}`,`Apply the ideas in ${lesson.title}`,`Check your understanding`]).map((x:any,i:number)=><li key={i} className="flex gap-3 text-slate-600 dark:text-slate-300"><CheckCircle2 className="mt-1 h-5 w-5 shrink-0 text-emerald-600"/>{x}</li>)}</ul></section><section className="mt-10"><h2 className="text-2xl font-extrabold text-[#151A3A] dark:text-white">Lesson</h2><div className="mt-5"><LessonContent content={notes}/></div></section>{!!lesson.key_points?.length&&<section className="mt-10 rounded-2xl bg-stone-50 p-6 dark:bg-[#151A3A]"><h2 className="text-xl font-extrabold text-[#151A3A] dark:text-white">Key points</h2><ul className="mt-4 space-y-2 text-slate-700 dark:text-slate-200">{lesson.key_points.map((x:any,i:number)=><li key={i} className="flex gap-2"><span>•</span>{x}</li>)}</ul></section>}</main><aside className="h-fit rounded-2xl border border-stone-200 bg-stone-50 p-5 dark:border-slate-700 dark:bg-[#151A3A]"><div className="flex items-center gap-2 font-extrabold text-[#151A3A] dark:text-white"><Sparkles className="h-5 w-5"/>THE GUIDE Teacher</div>{teaching?<div className="mt-4 flex items-center gap-2 text-sm text-slate-500"><Loader2 className="h-4 w-4 animate-spin"/>Preparing an explanation…</div>:<div className="mt-4 whitespace-pre-wrap text-sm leading-6 text-slate-600 dark:text-slate-300">{teacherText||'Read the lesson, then use Practice to check your understanding.'}</div>}<button onClick={()=>setActiveTab('practice')} className="mt-5 w-full rounded-xl bg-[#151A3A] px-4 py-2.5 text-sm font-bold text-white">Go to practice</button></aside></div>}
 {activeTab==='practice'&&<div className="p-6 sm:p-8">{!questions.length?<div className="mx-auto max-w-xl rounded-2xl border border-dashed border-stone-300 p-10 text-center dark:border-slate-700"><h2 className="text-xl font-extrabold text-[#151A3A] dark:text-white">Practice this lesson</h2><p className="mt-2 text-sm leading-6 text-slate-500">There are no stored questions attached to this topic yet. You can generate a lesson-specific practice set from the teaching material.</p><button onClick={generatePractice} disabled={!token||practiceLoading} className="mt-5 rounded-xl bg-[#151A3A] px-5 py-3 text-sm font-bold text-white disabled:opacity-50">{practiceLoading?'Generating practice…':'Generate practice set'}</button></div>:<div className="mx-auto max-w-3xl"><div className="mb-4 flex items-center justify-between text-sm text-slate-500"><span>Question {qi+1} of {questions.length}</span><span className="font-bold text-[#151A3A] dark:text-white">Score {score}</span></div><div className="rounded-2xl border border-stone-200 p-6 dark:border-slate-700"><p className="font-bold leading-7 text-slate-900 dark:text-white">{currentQ.question_text}</p>{currentQ.question_image_url&&<img src={currentQ.question_image_url} alt="Question" className="mt-4 max-h-72 rounded-lg object-contain"/>}<div className="mt-5 space-y-3">{opts.map((o:any)=><button key={o.id} disabled={!!selected} onClick={()=>selectAnswer(o.id)} className={`w-full rounded-xl border px-4 py-3 text-left ${selected?(o.id===correct?'border-emerald-300 bg-emerald-50 text-emerald-800':o.id===selected?'border-red-300 bg-red-50 text-red-800':'border-stone-200 text-slate-500'):'border-stone-200 hover:border-[#151A3A] dark:border-slate-700 dark:text-white'}`}><b className="mr-2">{o.id}.</b>{o.text}</button>)}</div>{selected&&<div className="mt-5 rounded-xl bg-stone-50 p-4 text-sm leading-6 text-slate-700 dark:bg-[#151A3A] dark:text-slate-200"><b>{selected===correct?'Correct!':'Not quite.'}</b>{currentQ.explanation&&<div className="mt-1">{currentQ.explanation}</div>}</div>}<div className="mt-5 flex justify-end"><button onClick={nextQuestion} disabled={qi===questions.length-1||!selected} className="rounded-xl bg-[#151A3A] px-5 py-2.5 text-sm font-bold text-white disabled:opacity-40">Next question <ChevronRight className="inline h-4 w-4"/></button></div></div></div>}</div>}
 {activeTab==='video'&&<div className="p-6">{lesson.video_url?<video ref={videoRef} controls className="aspect-video w-full rounded-xl bg-black" src={lesson.video_url}/>:<div className="flex aspect-video items-center justify-center rounded-xl bg-stone-100 text-slate-500 dark:bg-slate-900">No video has been uploaded for this lesson yet.</div>}</div>}
 {activeTab==='resources'&&<div className="p-6"><div className="rounded-xl border border-dashed border-stone-300 p-8 text-center text-sm text-slate-500 dark:border-slate-700"><Download className="mx-auto h-6 w-6 mb-2"/>No additional resources are attached to this lesson yet.</div></div>}
 </div><div className="flex flex-wrap items-center justify-between gap-3"><button disabled={!previous} onClick={()=>goTo(previous)} className="inline-flex items-center gap-2 rounded-xl border border-stone-300 bg-white px-4 py-2.5 text-sm font-bold text-slate-700 disabled:opacity-40"><ChevronLeft className="h-4 w-4"/>Previous</button><button onClick={markComplete} disabled={completed} className={`inline-flex items-center gap-2 rounded-xl px-5 py-2.5 text-sm font-bold ${completed?'bg-emerald-100 text-emerald-700':'bg-[#151A3A] text-white'}`}><CheckCircle2 className="h-4 w-4"/>{completed?'Completed':'Mark complete'}</button><button disabled={!next} onClick={()=>goTo(next)} className="inline-flex items-center gap-2 rounded-xl border border-stone-300 bg-white px-4 py-2.5 text-sm font-bold text-slate-700 disabled:opacity-40">Next<ChevronRight className="h-4 w-4"/></button></div></div>
}
