-- Restore ten more malformed Mathematics rows from matching public JAMB archive copies.
-- Rows with contradictory third-party keys or unrecoverable diagrams remain quarantined.

update public.past_questions set question_text='Find the solution of the equation x - 8√x + 15 = 0.',options='[{"id":"A","text":"3, 5"},{"id":"B","text":"-3, -5"},{"id":"C","text":"9, 25"},{"id":"D","text":"-9, 25"}]'::jsonb,correct_answer=to_jsonb('C'::text),question_type='mcq',year=1990,is_active=true,answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='dbc9bc72-3739-46ff-b831-61dba6975150' and correct_answer is null and source='storage:256ba2ee-b872-4024-bf35-ef96c6a3a4c7';
update public.past_questions set question_text='Find the missing value in the table for y = 4 - 3x - x³ when x = -3.',options='[{"id":"A","text":"-32"},{"id":"B","text":"-14"},{"id":"C","text":"40"},{"id":"D","text":"22"},{"id":"E","text":"37"}]'::jsonb,correct_answer=to_jsonb('C'::text),question_type='mcq',year=1985,is_active=true,answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='51cf0a5d-8c50-4ba3-a492-abeb9b0b17fb' and correct_answer is null and source='storage:256ba2ee-b872-4024-bf35-ef96c6a3a4c7';
update public.past_questions set question_text='Find the rate of change of the volume V of a sphere with respect to its radius r when r = 1.',options='[{"id":"A","text":"12π"},{"id":"B","text":"4π"},{"id":"C","text":"24π"},{"id":"D","text":"8π"}]'::jsonb,correct_answer=to_jsonb('B'::text),question_type='mcq',year=2001,is_active=true,answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='81d9a721-e723-4836-9a79-c74ca95c6d01' and correct_answer is null and source='storage:256ba2ee-b872-4024-bf35-ef96c6a3a4c7';
update public.past_questions set question_text='The number of goals scored by a football team in 20 matches is: goals 0,1,2,3,4,5 with corresponding match frequencies 3,5,7,4,1,0. What are the mean and mode respectively?',options='[{"id":"A","text":"(1.75, 5)"},{"id":"B","text":"(1.75, 2)"},{"id":"C","text":"(1.75, 1)"},{"id":"D","text":"(2, 2)"},{"id":"E","text":"(2, 1)"}]'::jsonb,correct_answer=to_jsonb('B'::text),question_type='mcq',year=1985,is_active=true,answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='01c85802-36cf-451e-b949-7c05c515dff4' and correct_answer is null and source='storage:256ba2ee-b872-4024-bf35-ef96c6a3a4c7';
update public.past_questions set question_text='Find the midpoint of the line joining P(-3, 5) and Q(5, -3).',options='[{"id":"A","text":"(1, 1)"},{"id":"B","text":"(2, 2)"},{"id":"C","text":"(4, 4)"},{"id":"D","text":"(4, -4)"}]'::jsonb,correct_answer=to_jsonb('A'::text),question_type='mcq',year=2004,is_active=true,answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='dbc13861-2b4c-414c-a431-1d2bc94983cd' and correct_answer is null and source='storage:256ba2ee-b872-4024-bf35-ef96c6a3a4c7';
update public.past_questions set question_text='Find the values of m which make the quadratic function x² + 2(m + 1)x + m + 3 a perfect square.',options='[{"id":"A","text":"-1, 1"},{"id":"B","text":"-1, 2"},{"id":"C","text":"1, -2"},{"id":"D","text":"2, -2"}]'::jsonb,correct_answer=to_jsonb('C'::text),question_type='mcq',is_active=true,answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='d4b643f5-a5cf-483d-ab11-b54d9065c1be' and correct_answer is null and source='storage:256ba2ee-b872-4024-bf35-ef96c6a3a4c7';
update public.past_questions set question_text='Two variables x and y are such that dy/dx = 4x - 3 and y = 5 when x = 2. Find y in terms of x.',options='[{"id":"A","text":"2x² - 3x + 5"},{"id":"B","text":"2x² - 3x + 3"},{"id":"C","text":"2x² - 3x"},{"id":"D","text":"4"}]'::jsonb,correct_answer=to_jsonb('B'::text),question_type='mcq',year=1995,is_active=true,answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='aad9ae4b-6eb6-40f7-abaf-ba9fa427d24d' and correct_answer is null and source='storage:256ba2ee-b872-4024-bf35-ef96c6a3a4c7';
update public.past_questions set question_text='The angle of a sector of a circle of radius 10.5 cm is 48°. Calculate the perimeter of the sector.',options='[{"id":"A","text":"8.8 cm"},{"id":"B","text":"25.4 cm"},{"id":"C","text":"25.6 cm"},{"id":"D","text":"29.8 cm"}]'::jsonb,correct_answer=to_jsonb('D'::text),question_type='mcq',year=1990,is_active=true,answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='bb039190-9766-44af-be17-6b6063dd9853' and correct_answer is null and source='storage:256ba2ee-b872-4024-bf35-ef96c6a3a4c7';
update public.past_questions set question_text='y is inversely proportional to x and y = 4 when x = 1/2. Find x when y = 10.',options='[{"id":"A","text":"2"},{"id":"B","text":"10"},{"id":"C","text":"1/5"},{"id":"D","text":"1/10"}]'::jsonb,correct_answer=to_jsonb('C'::text),question_type='mcq',is_active=true,answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='ebee982a-973c-4237-9890-abe49e6928b5' and correct_answer is null and source='storage:256ba2ee-b872-4024-bf35-ef96c6a3a4c7';
update public.past_questions set question_text='A sum of money was invested at 8% per annum simple interest. If after 4 years the money amounts to ₦330.00, find the amount originally invested.',options='[{"id":"A","text":"₦180.00"},{"id":"B","text":"₦165.00"},{"id":"C","text":"₦150.00"},{"id":"D","text":"₦250.00"},{"id":"E","text":"₦200.00"}]'::jsonb,correct_answer=to_jsonb('D'::text),question_type='mcq',year=1985,is_active=true,answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='e6623621-c4f2-4bcb-8ebf-cfd8f8ba07fd' and correct_answer is null and source='storage:256ba2ee-b872-4024-bf35-ef96c6a3a4c7';
