-- Restore ten malformed Physics extraction rows from matching public JAMB archive copies.
-- Every row remains tied to its original Supabase Storage source.

update public.past_questions set question_text='The equation of a transverse wave traveling along a string is given by y = 0.3 sin (0.5x - 50t), where y and x are in cm and t is in seconds. Find the maximum displacement of the particles from equilibrium position.',options='[{"id":"A","text":"50.0 cm"},{"id":"B","text":"2.5 cm"},{"id":"C","text":"0.5 cm"},{"id":"D","text":"0.3 cm"}]'::jsonb,correct_answer=to_jsonb('D'::text),question_type='mcq',year=1994,is_active=true,answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='03f59166-0fc7-45dc-89ea-8322967d1c78' and correct_answer is null and source like 'storage:%';
update public.past_questions set question_text='A string is fastened tightly between two walls 24 cm apart. The wavelength of the second overtone is',options='[{"id":"A","text":"24 cm"},{"id":"B","text":"16 cm"},{"id":"C","text":"12 cm"},{"id":"D","text":"8 cm"}]'::jsonb,correct_answer=to_jsonb('B'::text),question_type='mcq',year=2001,is_active=true,answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='0cc55f91-4180-48d1-8e8a-3617661f3320' and correct_answer is null and source like 'storage:%';
update public.past_questions set question_text='A 100 kg box is pushed along a road with a force of 500 N. If the box moves with a uniform velocity, find the coefficient of friction between the box and the road. Take g = 10 m/s².',options='[{"id":"A","text":"0.4"},{"id":"B","text":"1.0"},{"id":"C","text":"0.8"},{"id":"D","text":"0.5"}]'::jsonb,correct_answer=to_jsonb('D'::text),question_type='mcq',year=2004,is_active=true,answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='1141313a-82d5-4111-87d2-17452d09ce1f' and correct_answer is null and source like 'storage:%';
update public.past_questions set question_text='When the brakes in a car are applied, the frictional force on the tyres is',options='[{"id":"A","text":"a disadvantage because it is in the direction of motion"},{"id":"B","text":"a disadvantage because it is opposite to the direction of motion"},{"id":"C","text":"an advantage because it is in the direction of motion"},{"id":"D","text":"an advantage because it is opposite to the direction of motion"}]'::jsonb,correct_answer=to_jsonb('D'::text),question_type='mcq',year=1999,is_active=true,answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='34cd468a-7c3b-494d-839a-856c40e65b4e' and correct_answer is null and source like 'storage:%';
update public.past_questions set question_text='The heat produced in a conductor carrying an electric current is',options='[{"id":"A","text":"inversely proportional to the current and resistance"},{"id":"B","text":"directly proportional to the current, resistance and time"},{"id":"C","text":"inversely proportional to the square of the current, resistance and time"},{"id":"D","text":"directly proportional to the square of the current, resistance and time"}]'::jsonb,correct_answer=to_jsonb('D'::text),question_type='mcq',year=1992,is_active=true,answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='3b61ba50-3045-497a-a5b3-2f211e4b4dc9' and correct_answer is null and source like 'storage:%';
update public.past_questions set question_text='Dispersion of light by a glass prism is due to the',options='[{"id":"A","text":"different colours of glass"},{"id":"B","text":"different speeds of the various colours in glass"},{"id":"C","text":"defects in the glass"},{"id":"D","text":"high density of the glass"}]'::jsonb,correct_answer=to_jsonb('B'::text),question_type='mcq',year=1989,is_active=true,answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='3fece83e-25c9-4397-b358-0c34d89c32d0' and correct_answer is null and source like 'storage:%';
update public.past_questions set question_text='To obtain a magnification of 2.5, how far should an object be placed from the pole of a thin converging lens of focal length 0.20 m?',options='[{"id":"A","text":"0.13 m"},{"id":"B","text":"0.25 m"},{"id":"C","text":"0.28 m"},{"id":"D","text":"0.50 m"}]'::jsonb,correct_answer=to_jsonb('C'::text),question_type='mcq',year=1988,is_active=true,answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='5554afe2-7062-4b31-9dfa-50cd1975db2d' and correct_answer is null and source like 'storage:%';
update public.past_questions set question_text='The saturated vapour pressure of a liquid increases when the',options='[{"id":"A","text":"volume increases"},{"id":"B","text":"volume decreases"},{"id":"C","text":"temperature increases"},{"id":"D","text":"temperature decreases"}]'::jsonb,correct_answer=to_jsonb('C'::text),question_type='mcq',year=1991,is_active=true,answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='5da94687-ffce-42d0-888e-53a5d3ac7a23' and correct_answer is null and source like 'storage:%';
update public.past_questions set question_text='For a short-sighted person, light rays from a distant point object are focused',options='[{"id":"A","text":"in front of the retina"},{"id":"B","text":"on the retina by a converging lens"},{"id":"C","text":"behind the retina by a diverging lens"},{"id":"D","text":"in front of the retina at a distance 2F from the lens"}]'::jsonb,correct_answer=to_jsonb('A'::text),question_type='mcq',year=1990,is_active=true,answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='6a26a11a-a488-4558-adf2-8a8ffedf925e' and correct_answer is null and source like 'storage:%';
update public.past_questions set question_text='A piece of wood floats inside water at room temperature with a fraction of it above the liquid surface. As the temperature of the water is raised, the fraction of the wood above the surface',options='[{"id":"A","text":"decreases because the density of water decreases with temperature"},{"id":"B","text":"increases because the density of water decreases with temperature"},{"id":"C","text":"decreases because the density of water increases with temperature"},{"id":"D","text":"increases because the density of water increases with temperature"}]'::jsonb,correct_answer=to_jsonb('A'::text),question_type='mcq',year=1995,is_active=true,answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='5b2e6321-a537-4544-b6b8-baf3e0db944f' and correct_answer is null and source like 'storage:%';
