-- Restore ten additional malformed Physics rows from matching public JAMB archive copies.
-- Conflicting/ambiguous archive-key rows are deliberately excluded.
-- Every row remains tied to its original Supabase Storage source.

update public.past_questions set question_text='When a known standard resistor of 2.0 Ω is connected to the 0.0 cm end of a metre bridge, the balance point is found to be at 55.0 cm. Find the unknown resistance.',options='[{"id":"A","text":"1.10 Ω"},{"id":"B","text":"1.64 Ω"},{"id":"C","text":"2.44 Ω"},{"id":"D","text":"27.50 Ω"}]'::jsonb,correct_answer=to_jsonb('B'::text),question_type='mcq',year=2018,is_active=true,answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='2a113bb2-a4e6-4e26-9990-02af6aaffeed' and correct_answer is null and source='storage:787b6ff8-b879-4c0d-b2dd-8b51c119446f';
update public.past_questions set question_text='An ebonite rod rubbed with fur attracts a glass rod rubbed with silk because',options='[{"id":"A","text":"ebonite has a negative charge while glass has a positive charge"},{"id":"B","text":"ebonite has a positive charge while glass has a negative charge"},{"id":"C","text":"both have negative charges"},{"id":"D","text":"both have positive charges"}]'::jsonb,correct_answer=to_jsonb('A'::text),question_type='mcq',year=1998,is_active=true,answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='dbeb5436-ac63-4d8f-9f98-53335220b126' and correct_answer is null and source='storage:787b6ff8-b879-4c0d-b2dd-8b51c119446f';
update public.past_questions set question_text='A spectrum of sunlight is said to be impure when',options='[{"id":"A","text":"it is made up of only three colours"},{"id":"B","text":"there is no red colour in it"},{"id":"C","text":"the different colours overlap"},{"id":"D","text":"it does not contain white light"}]'::jsonb,correct_answer=to_jsonb('C'::text),question_type='mcq',year=1988,is_active=true,answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='7c43f6a0-9294-4e4a-a447-84f3a74e77a0' and correct_answer is null and source='storage:787b6ff8-b879-4c0d-b2dd-8b51c119446f';
update public.past_questions set question_text='The pitch of an acoustic device can be increased by',options='[{"id":"A","text":"increasing the frequency"},{"id":"B","text":"increasing the amplitude"},{"id":"C","text":"decreasing the loudness"},{"id":"D","text":"decreasing the intensity"}]'::jsonb,correct_answer=to_jsonb('A'::text),question_type='mcq',year=1995,is_active=true,answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='a28c127f-bcc1-4d6b-b7ab-551bd14278d7' and correct_answer is null and source='storage:787b6ff8-b879-4c0d-b2dd-8b51c119446f';
update public.past_questions set question_text='The difference between sound waves and light waves is that sound waves',options='[{"id":"A","text":"are transverse while light waves are longitudinal"},{"id":"B","text":"require a medium to travel while light waves do not"},{"id":"C","text":"can be diffracted but light waves cannot"},{"id":"D","text":"cannot be reflected but light waves can"}]'::jsonb,correct_answer=to_jsonb('B'::text),question_type='mcq',year=1995,is_active=true,answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='9d0cf7cb-8432-46f2-b15b-396be952ca51' and correct_answer is null and source='storage:787b6ff8-b879-4c0d-b2dd-8b51c119446f';
update public.past_questions set question_text='The graphite rods surrounding the uranium fuel rods in a nuclear reactor are used to',options='[{"id":"A","text":"absorb the neutrons and hence halt the nuclear process"},{"id":"B","text":"create the neutrons and hence slow up the nuclear process"},{"id":"C","text":"slow down the neutrons and hence slow up the nuclear process"},{"id":"D","text":"speed up the neutrons and hence speed up the nuclear process"}]'::jsonb,correct_answer=to_jsonb('C'::text),question_type='mcq',year=1997,is_active=true,answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='9fb805a9-2b82-46c2-9edb-6a533a824739' and correct_answer is null and source='storage:787b6ff8-b879-4c0d-b2dd-8b51c119446f';
update public.past_questions set question_text='Which of the following eye defects can be corrected using a cylindrical lens?',options='[{"id":"A","text":"Myopia"},{"id":"B","text":"Astigmatism"},{"id":"C","text":"Presbyopia"},{"id":"D","text":"Chromatic aberration"}]'::jsonb,correct_answer=to_jsonb('B'::text),question_type='mcq',year=2002,is_active=true,answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='af267877-f33f-4355-9021-a6c07ee82e6b' and correct_answer is null and source='storage:787b6ff8-b879-4c0d-b2dd-8b51c119446f';
update public.past_questions set question_text='A radioactive substance has a half-life of 80 days. If the initial number of atoms in the sample is 6.0 × 10¹⁰, how many atoms would remain at the end of 320 days?',options='[{"id":"A","text":"3.75 × 10⁹"},{"id":"B","text":"7.50 × 10⁹"},{"id":"C","text":"3.00 × 10¹⁰"},{"id":"D","text":"5.63 × 10¹⁰"}]'::jsonb,correct_answer=to_jsonb('A'::text),question_type='mcq',year=1998,is_active=true,answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='fc7421ff-0631-4566-aa3e-64baa98a56d1' and correct_answer is null and source='storage:787b6ff8-b879-4c0d-b2dd-8b51c119446f';
update public.past_questions set question_text='An electron of charge 1.6 × 10⁻¹⁹ C and mass 9.1 × 10⁻³¹ kg is accelerated between two metal plates with a velocity of 4 × 10⁷ m s⁻¹. The potential difference between the plates is',options='[{"id":"A","text":"4.55 × 10³ V"},{"id":"B","text":"4.55 × 10² V"},{"id":"C","text":"9.10 × 10¹ V"},{"id":"D","text":"4.55 × 10¹ V"}]'::jsonb,correct_answer=to_jsonb('A'::text),question_type='mcq',year=2000,is_active=true,answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='ffad6906-39a4-4704-8c84-52d0b0224f4d' and correct_answer is null and source='storage:787b6ff8-b879-4c0d-b2dd-8b51c119446f';
update public.past_questions set question_text='The maximum permissible current through a galvanometer G of internal resistance 10 Ω is 0.05 A. A resistance R is used to convert G into a voltmeter with a maximum reading of 100 V. Find the value of R and how it is connected to G.',options='[{"id":"A","text":"20,000 Ω in parallel"},{"id":"B","text":"19,990 Ω in series"},{"id":"C","text":"1,990 Ω in series"},{"id":"D","text":"100 Ω in series"}]'::jsonb,correct_answer=to_jsonb('C'::text),question_type='mcq',is_active=true,answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='b1c99869-d8f1-48e3-b5f7-7901d5ced7ed' and correct_answer is null and source='storage:787b6ff8-b879-4c0d-b2dd-8b51c119446f';
