-- The previous admin-read template used `auth.uid() is not null`, which made
-- every authenticated user satisfy policies intended only for administrators.
-- Public/owner-specific policies are left intact; only the admin-read path is
-- restricted here.

drop policy if exists achievements_admin_read on public.achievements; create policy achievements_admin_read on public.achievements for select to authenticated using (has_role('admin'::text) or has_role('super_admin'::text));
drop policy if exists assignments_admin_read on public.assignments; create policy assignments_admin_read on public.assignments for select to authenticated using (has_role('admin'::text) or has_role('super_admin'::text));
drop policy if exists audit_logs_admin_read on public.audit_logs; create policy audit_logs_admin_read on public.audit_logs for select to authenticated using (has_role('admin'::text) or has_role('super_admin'::text));
drop policy if exists badges_admin_read on public.badges; create policy badges_admin_read on public.badges for select to authenticated using (has_role('admin'::text) or has_role('super_admin'::text));
drop policy if exists class_subjects_admin_read on public.class_subjects; create policy class_subjects_admin_read on public.class_subjects for select to authenticated using (has_role('admin'::text) or has_role('super_admin'::text));
drop policy if exists classes_admin_read on public.classes; create policy classes_admin_read on public.classes for select to authenticated using (has_role('admin'::text) or has_role('super_admin'::text));
drop policy if exists coupon_usages_admin_read on public.coupon_usages; create policy coupon_usages_admin_read on public.coupon_usages for select to authenticated using (has_role('admin'::text) or has_role('super_admin'::text));
drop policy if exists coupons_admin_read on public.coupons; create policy coupons_admin_read on public.coupons for select to authenticated using (has_role('admin'::text) or has_role('super_admin'::text));
drop policy if exists documents_admin_read on public.documents; create policy documents_admin_read on public.documents for select to authenticated using (has_role('admin'::text) or has_role('super_admin'::text));
drop policy if exists education_levels_admin_read on public.education_levels; create policy education_levels_admin_read on public.education_levels for select to authenticated using (has_role('admin'::text) or has_role('super_admin'::text));
drop policy if exists education_systems_admin_read on public.education_systems; create policy education_systems_admin_read on public.education_systems for select to authenticated using (has_role('admin'::text) or has_role('super_admin'::text));
drop policy if exists exam_answers_admin_read on public.exam_answers; create policy exam_answers_admin_read on public.exam_answers for select to authenticated using (has_role('admin'::text) or has_role('super_admin'::text));
drop policy if exists exam_questions_admin_read on public.exam_questions; create policy exam_questions_admin_read on public.exam_questions for select to authenticated using (has_role('admin'::text) or has_role('super_admin'::text));
drop policy if exists exams_admin_read on public.exams; create policy exams_admin_read on public.exams for select to authenticated using (has_role('admin'::text) or has_role('super_admin'::text));
drop policy if exists invoices_admin_read on public.invoices; create policy invoices_admin_read on public.invoices for select to authenticated using (has_role('admin'::text) or has_role('super_admin'::text));
drop policy if exists leaderboards_admin_read on public.leaderboards; create policy leaderboards_admin_read on public.leaderboards for select to authenticated using (has_role('admin'::text) or has_role('super_admin'::text));
drop policy if exists lesson_resources_admin_read on public.lesson_resources; create policy lesson_resources_admin_read on public.lesson_resources for select to authenticated using (has_role('admin'::text) or has_role('super_admin'::text));
drop policy if exists library_resources_admin_read on public.library_resources; create policy library_resources_admin_read on public.library_resources for select to authenticated using (has_role('admin'::text) or has_role('super_admin'::text));
drop policy if exists live_classes_admin_read on public.live_classes; create policy live_classes_admin_read on public.live_classes for select to authenticated using (has_role('admin'::text) or has_role('super_admin'::text));
drop policy if exists parent_children_admin_read on public.parent_children; create policy parent_children_admin_read on public.parent_children for select to authenticated using (has_role('admin'::text) or has_role('super_admin'::text));
drop policy if exists parents_admin_read on public.parents; create policy parents_admin_read on public.parents for select to authenticated using (has_role('admin'::text) or has_role('super_admin'::text));
drop policy if exists past_questions_admin_read on public.past_questions; create policy past_questions_admin_read on public.past_questions for select to authenticated using (has_role('admin'::text) or has_role('super_admin'::text));
drop policy if exists payment_methods_admin_read on public.payment_methods; create policy payment_methods_admin_read on public.payment_methods for select to authenticated using (has_role('admin'::text) or has_role('super_admin'::text));
drop policy if exists points_history_admin_read on public.points_history; create policy points_history_admin_read on public.points_history for select to authenticated using (has_role('admin'::text) or has_role('super_admin'::text));
drop policy if exists programs_admin_read on public.programs; create policy programs_admin_read on public.programs for select to authenticated using (has_role('admin'::text) or has_role('super_admin'::text));
drop policy if exists questions_admin_read on public.questions; create policy questions_admin_read on public.questions for select to authenticated using (has_role('admin'::text) or has_role('super_admin'::text));
drop policy if exists quiz_questions_admin_read on public.quiz_questions; create policy quiz_questions_admin_read on public.quiz_questions for select to authenticated using (has_role('admin'::text) or has_role('super_admin'::text));
drop policy if exists quizzes_admin_read on public.quizzes; create policy quizzes_admin_read on public.quizzes for select to authenticated using (has_role('admin'::text) or has_role('super_admin'::text));
drop policy if exists reports_admin_read on public.reports; create policy reports_admin_read on public.reports for select to authenticated using (has_role('admin'::text) or has_role('super_admin'::text));
drop policy if exists rewards_admin_read on public.rewards; create policy rewards_admin_read on public.rewards for select to authenticated using (has_role('admin'::text) or has_role('super_admin'::text));
drop policy if exists roles_admin_read on public.roles; create policy roles_admin_read on public.roles for select to authenticated using (has_role('admin'::text) or has_role('super_admin'::text));
drop policy if exists school_classes_admin_read on public.school_classes; create policy school_classes_admin_read on public.school_classes for select to authenticated using (has_role('admin'::text) or has_role('super_admin'::text));
drop policy if exists school_students_admin_read on public.school_students; create policy school_students_admin_read on public.school_students for select to authenticated using (has_role('admin'::text) or has_role('super_admin'::text));
drop policy if exists school_teachers_admin_read on public.school_teachers; create policy school_teachers_admin_read on public.school_teachers for select to authenticated using (has_role('admin'::text) or has_role('super_admin'::text));
drop policy if exists schools_admin_read on public.schools; create policy schools_admin_read on public.schools for select to authenticated using (has_role('admin'::text) or has_role('super_admin'::text));
drop policy if exists student_points_admin_read on public.student_points; create policy student_points_admin_read on public.student_points for select to authenticated using (has_role('admin'::text) or has_role('super_admin'::text));
drop policy if exists subjects_admin_read on public.subjects; create policy subjects_admin_read on public.subjects for select to authenticated using (has_role('admin'::text) or has_role('super_admin'::text));
drop policy if exists subscription_plans_admin_read on public.subscription_plans; create policy subscription_plans_admin_read on public.subscription_plans for select to authenticated using (has_role('admin'::text) or has_role('super_admin'::text));
drop policy if exists subtopics_admin_read on public.subtopics; create policy subtopics_admin_read on public.subtopics for select to authenticated using (has_role('admin'::text) or has_role('super_admin'::text));
drop policy if exists system_settings_admin_read on public.system_settings; create policy system_settings_admin_read on public.system_settings for select to authenticated using (has_role('admin'::text) or has_role('super_admin'::text));
drop policy if exists teacher_earnings_admin_read on public.teacher_earnings; create policy teacher_earnings_admin_read on public.teacher_earnings for select to authenticated using (has_role('admin'::text) or has_role('super_admin'::text));
drop policy if exists teachers_admin_read on public.teachers; create policy teachers_admin_read on public.teachers for select to authenticated using (has_role('admin'::text) or has_role('super_admin'::text));
drop policy if exists terms_admin_read on public.terms; create policy terms_admin_read on public.terms for select to authenticated using (has_role('admin'::text) or has_role('super_admin'::text));
drop policy if exists topics_admin_read on public.topics; create policy topics_admin_read on public.topics for select to authenticated using (has_role('admin'::text) or has_role('super_admin'::text));
drop policy if exists transactions_admin_read on public.transactions; create policy transactions_admin_read on public.transactions for select to authenticated using (has_role('admin'::text) or has_role('super_admin'::text));
drop policy if exists user_rewards_admin_read on public.user_rewards; create policy user_rewards_admin_read on public.user_rewards for select to authenticated using (has_role('admin'::text) or has_role('super_admin'::text));
drop policy if exists user_roles_admin_read on public.user_roles; create policy user_roles_admin_read on public.user_roles for select to authenticated using (has_role('admin'::text) or has_role('super_admin'::text));
