-- Restore ten additional malformed Mathematics rows from matching public JAMB archive copies.
-- Every row remains tied to its original Supabase Storage source.

update public.past_questions set question_text='If x varies directly as y³ and x = 2 when y = 1, find x when y = 5.',options='[{"id":"A","text":"2"},{"id":"B","text":"10"},{"id":"C","text":"125"},{"id":"D","text":"250"}]'::jsonb,correct_answer=to_jsonb('D'::text),question_type='mcq',is_active=true,answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='cbfec933-638d-41dd-9a5b-16bc86e20da3' and correct_answer is null and source='storage:256ba2ee-b872-4024-bf35-ef96c6a3a4c7';
update public.past_questions set question_text='Find the values of x where the curve y = x³ + 2x² - 5x - 6 crosses the x-axis.',options='[{"id":"A","text":"-2, -1 and 3"},{"id":"B","text":"-2, 1 and -3"},{"id":"C","text":"2, -1 and -3"},{"id":"D","text":"2, 1 and 3"}]'::jsonb,correct_answer=to_jsonb('C'::text),question_type='mcq',is_active=true,answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='e0bc6e10-4717-4c0d-b57c-a0793a72f083' and correct_answer is null and source='storage:256ba2ee-b872-4024-bf35-ef96c6a3a4c7';
update public.past_questions set question_text='Find the positive number n such that thrice its square is equal to twelve times the number.',options='[{"id":"A","text":"1"},{"id":"B","text":"2"},{"id":"C","text":"3"},{"id":"D","text":"4"}]'::jsonb,correct_answer=to_jsonb('D'::text),question_type='mcq',year=1991,is_active=true,answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='a5b9b92b-67cc-48e9-8d5c-2d30b1b087c0' and correct_answer is null and source='storage:256ba2ee-b872-4024-bf35-ef96c6a3a4c7';
update public.past_questions set question_text='What must be added to 4x² - 4 to make it a perfect square?',options='[{"id":"A","text":"-1/x²"},{"id":"B","text":"1/x²"},{"id":"C","text":"1"},{"id":"D","text":"-1"}]'::jsonb,correct_answer=to_jsonb('B'::text),question_type='mcq',is_active=true,answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='9731c368-f9dc-4991-a1cb-f134a70a7423' and correct_answer is null and source='storage:256ba2ee-b872-4024-bf35-ef96c6a3a4c7';
update public.past_questions set question_text='Tunde and Shola can do a piece of work in 18 days. Tunde can do it alone in x days, while Shola takes 15 days longer to do it alone. Which of the following equations is satisfied by x?',options='[{"id":"A","text":"x² - 5x - 10 = 0"},{"id":"B","text":"x² - 20x + 360 = 0"},{"id":"C","text":"x² - 21x - 270 = 0"},{"id":"D","text":"3x² - 65x + 362 = 0"}]'::jsonb,correct_answer=to_jsonb('C'::text),question_type='mcq',year=1984,is_active=true,answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='fbc71a16-97a3-4341-9c24-1f50361bc0b2' and correct_answer is null and source='storage:256ba2ee-b872-4024-bf35-ef96c6a3a4c7';
update public.past_questions set question_text='The mean of ten positive numbers is 16. When another number is added, the mean becomes 18. Find the eleventh number.',options='[{"id":"A","text":"3"},{"id":"B","text":"16"},{"id":"C","text":"18"},{"id":"D","text":"38"}]'::jsonb,correct_answer=to_jsonb('D'::text),question_type='mcq',year=1990,is_active=true,answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='52b8aa8d-f12f-470c-86ec-b2b5aed7224d' and correct_answer is null and source='storage:256ba2ee-b872-4024-bf35-ef96c6a3a4c7';
update public.past_questions set question_text='A container has 30 gold medals, 22 silver medals and 18 bronze medals. If one medal is selected at random from the container, what is the probability that it is not a gold medal?',options='[{"id":"A","text":"4/7"},{"id":"B","text":"3/7"},{"id":"C","text":"11/35"},{"id":"D","text":"9/35"}]'::jsonb,correct_answer=to_jsonb('A'::text),question_type='mcq',is_active=true,answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='6e040990-d738-4890-b849-d45870877127' and correct_answer is null and source='storage:256ba2ee-b872-4024-bf35-ef96c6a3a4c7';
update public.past_questions set question_text='A cylindrical tank has a capacity of 3080 m³. What is the depth of the tank if the diameter of its base is 14 m? Take π = 22/7.',options='[{"id":"A","text":"23 m"},{"id":"B","text":"25 m"},{"id":"C","text":"20 m"},{"id":"D","text":"22 m"}]'::jsonb,correct_answer=to_jsonb('C'::text),question_type='mcq',year=2001,is_active=true,answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='c9a37580-adeb-49cc-9bc8-58047ab18d43' and correct_answer is null and source='storage:256ba2ee-b872-4024-bf35-ef96c6a3a4c7';
update public.past_questions set question_text='Factorize completely y³ - 4xy + xy³ - 4y.',options='[{"id":"A","text":"(x + xy)(y + 2)(y - 2)"},{"id":"B","text":"(y + xy)(y + 2)(y - 2)"},{"id":"C","text":"y(1 + x)(y + 2)(y - 2)"},{"id":"D","text":"y(1 - x)(y + 2)(y - 2)"}]'::jsonb,correct_answer=to_jsonb('C'::text),question_type='mcq',is_active=true,answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='7f2da6b1-a88d-4900-87c8-17666ead7ec3' and correct_answer is null and source='storage:256ba2ee-b872-4024-bf35-ef96c6a3a4c7';
update public.past_questions set question_text='Solve the equation 3x² + 6x - 2 = 0.',options='[{"id":"A","text":"x = -1 ± √3/3"},{"id":"B","text":"x = -1 ± √15/3"},{"id":"C","text":"x = -2 ± 2"},{"id":"D","text":"x = 3 ± √3/15"}]'::jsonb,correct_answer=to_jsonb('B'::text),question_type='mcq',year=1986,is_active=true,answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='40a9db7b-fbd9-46aa-b694-2d1efef65167' and correct_answer is null and source='storage:256ba2ee-b872-4024-bf35-ef96c6a3a4c7';
