-- Restore ten malformed Mathematics extraction rows from their matching public JAMB archive copies.
-- The rows remain tied to the original Supabase Storage source.

update public.past_questions set question_text='If two fair coins are tossed, what is the probability of getting at least one head?',options='[{"id":"A","text":"1/4"},{"id":"B","text":"1/2"},{"id":"C","text":"1"},{"id":"D","text":"2/3"},{"id":"E","text":"3/4"}]'::jsonb,correct_answer=to_jsonb('E'::text),question_type='mcq',year=1985,is_active=true,answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='08b9668f-d305-4ae6-b09f-5e2c59aba2d8' and correct_answer is null and source like 'storage:%';
update public.past_questions set question_text='A man invested a sum of N280.00 partly at 5% and partly at 4%. If the total interest is N12.80 per annum, find the amount invested at 5%.',options='[{"id":"A","text":"N14.00"},{"id":"B","text":"N120.00"},{"id":"C","text":"N140.00"},{"id":"D","text":"N160.00"}]'::jsonb,correct_answer=to_jsonb('D'::text),question_type='mcq',year=1992,is_active=true,answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='156f1375-9198-4508-82ec-e41a73ee878a' and correct_answer is null and source like 'storage:%';
update public.past_questions set question_text='The cost of dinner for a group of students is partly constant and partly varies directly as the number of students. If the cost is N74.00 when there are 20 students and N96.00 when there are 30 students, find the cost when there are 15 students.',options='[{"id":"A","text":"N68.50"},{"id":"B","text":"N63.00"},{"id":"C","text":"N60.00"},{"id":"D","text":"N52.00"}]'::jsonb,correct_answer=to_jsonb('B'::text),question_type='mcq',year=1989,is_active=true,answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='15df6ed0-d337-4ef2-9b35-ceee65e06e98' and correct_answer is null and source like 'storage:%';
update public.past_questions set question_text='A right circular cone has a base radius r cm and a vertical angle 2y°. The height of the cone is',options='[{"id":"A","text":"r tan y° cm"},{"id":"B","text":"r sin y° cm"},{"id":"C","text":"r cot y° cm"},{"id":"D","text":"r cos y° cm"},{"id":"E","text":"r cosec y° cm"}]'::jsonb,correct_answer=to_jsonb('C'::text),question_type='mcq',year=1984,is_active=true,answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='17b8bca6-03db-492d-80bb-85da77d356b0' and correct_answer is null and source like 'storage:%';
update public.past_questions set question_text='Factorize 4a² + 12ab - c² + 9b².',options='[{"id":"A","text":"4a(a - 3b) + (3b - c)²"},{"id":"B","text":"(2a + 3b - c)(2a + 3b + c)"},{"id":"C","text":"(2a - 3b - c)(2a - 3b + c)"},{"id":"D","text":"4a(a - 3b) + (3b + c)²"}]'::jsonb,correct_answer=to_jsonb('B'::text),question_type='mcq',year=1989,is_active=true,answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='1e288125-2ba2-40c8-9190-3ed9739b1843' and correct_answer is null and source like 'storage:%';
update public.past_questions set question_text='If the hypotenuse of a right-angled isosceles triangle is 2, what is the length of each of the other sides?',options='[{"id":"A","text":"√2"},{"id":"B","text":"1/√2"},{"id":"C","text":"2√2"},{"id":"D","text":"1"},{"id":"E","text":"√2 - 1"}]'::jsonb,correct_answer=to_jsonb('A'::text),question_type='mcq',year=1985,is_active=true,answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='1ec9b3b7-5189-47a4-9082-44bbde8a09a6' and correct_answer is null and source like 'storage:%';
update public.past_questions set question_text='A point P moves such that it is equidistant from the points Q and R. Find QR when PR = 8 cm and ∠PRQ = 30°.',options='[{"id":"A","text":"4 cm"},{"id":"B","text":"4√3 cm"},{"id":"C","text":"8 cm"},{"id":"D","text":"8√3 cm"}]'::jsonb,correct_answer=to_jsonb('D'::text),question_type='mcq',year=2001,is_active=true,answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='241c6991-a2da-4981-ba39-058f401f4671' and correct_answer is null and source like 'storage:%';
update public.past_questions set question_text='The sum of two numbers is twice their difference. If the difference of the numbers is p, find the larger of the two numbers.',options='[{"id":"A","text":"p/2"},{"id":"B","text":"3p/2"},{"id":"C","text":"5p/2"},{"id":"D","text":"3p"}]'::jsonb,correct_answer=to_jsonb('B'::text),question_type='mcq',year=1999,is_active=true,answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='399e505f-5062-4dc5-b6f3-05c70984c676' and correct_answer is null and source like 'storage:%';
update public.past_questions set question_text='If three angles of a quadrilateral are (3y - x - z)°, 3x°, and (2z - 2y - x)°, find the fourth angle in terms of x, y and z.',options='[{"id":"A","text":"(360 - x - y - z)°"},{"id":"B","text":"(360 + x + y - z)°"},{"id":"C","text":"(180 - x + y + z)°"},{"id":"D","text":"(180 + x + y + z)°"}]'::jsonb,correct_answer=to_jsonb('A'::text),question_type='mcq',year=1994,is_active=true,answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='3b11d4aa-5755-4c0c-96d0-a9342e2d3c70' and correct_answer is null and source like 'storage:%';
update public.past_questions set question_text='Simplify (√12 - √3)/(√12 + √3).',options='[{"id":"A","text":"0"},{"id":"B","text":"1/3"},{"id":"C","text":"3/5"},{"id":"D","text":"1"}]'::jsonb,correct_answer=to_jsonb('B'::text),question_type='mcq',year=2005,is_active=true,answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='45fb0bbf-3ebe-4bbb-a437-fe2008abe422' and correct_answer is null and source like 'storage:%';
