-- Deepen strict JAMB Government depth with existing storage-backed questions only.
-- Answers here were cross-validated against matching public JAMB archive/question-bank copies.

update public.past_questions set correct_answer=to_jsonb('A'::text),answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='03074e1b-7541-4df0-8fec-33de023513e7' and correct_answer is null and source like 'storage:%';
update public.past_questions set correct_answer=to_jsonb('B'::text),answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='04107a02-84bd-46fb-8095-f47b8cdc806d' and correct_answer is null and source like 'storage:%';
update public.past_questions set correct_answer=to_jsonb('B'::text),answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='067c15f8-763a-4288-b252-1104aeb7e929' and correct_answer is null and source like 'storage:%';
update public.past_questions set correct_answer=to_jsonb('D'::text),answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='084eb294-cb5c-4937-947c-b8ee35719d69' and correct_answer is null and source like 'storage:%';
update public.past_questions set correct_answer=to_jsonb('A'::text),answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='0cb78e76-18f6-4c65-bfda-a7cd75e9178b' and correct_answer is null and source like 'storage:%';
update public.past_questions set correct_answer=to_jsonb('D'::text),answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='0e2a39f9-3356-47a7-ab92-98920e698b87' and correct_answer is null and source like 'storage:%';
update public.past_questions set correct_answer=to_jsonb('C'::text),answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='11808741-5b6c-4674-8dc2-a7fa731c8b62' and correct_answer is null and source like 'storage:%';
update public.past_questions set correct_answer=to_jsonb('B'::text),answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='12759503-b7d4-4fea-8b63-6d5c7b7d1424' and correct_answer is null and source like 'storage:%';
update public.past_questions set correct_answer=to_jsonb('B'::text),answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='1566efb7-b27d-41cf-ac22-50d3c8f518de' and correct_answer is null and source like 'storage:%';
update public.past_questions set correct_answer=to_jsonb('B'::text),answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='161dc0d1-f1be-45db-9c03-04d6bf70788d' and correct_answer is null and source like 'storage:%';
