-- Restore ten more malformed Physics rows from matching public JAMB archive copies.
-- Conflicting or internally inconsistent archive-key rows remain quarantined.
-- Every learner-facing row retains its original Supabase Storage provenance.

update public.past_questions set question_text='A body rolls down a slope from a height of 100 m. Its velocity at the foot of the slope is 20 m s⁻¹. What percentage of its potential energy is converted into kinetic energy? Take g = 10 m s⁻².',options='[{"id":"A","text":"40%"},{"id":"B","text":"35%"},{"id":"C","text":"20%"},{"id":"D","text":"15%"}]'::jsonb,correct_answer=to_jsonb('C'::text),question_type='mcq',year=1987,is_active=true,answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='cc7f9f80-bee8-406d-b1b7-f783747553a1' and correct_answer is null and source='storage:787b6ff8-b879-4c0d-b2dd-8b51c119446f';
update public.past_questions set question_text='A heating coil rated at 1000 W is used to boil off 0.5 kg of boiling water. The latent heat of vaporization of water is 2.3 × 10⁶ J kg⁻¹. The time taken to boil off the water is',options='[{"id":"A","text":"1.15 × 10⁹ s"},{"id":"B","text":"1.15 × 10⁷ s"},{"id":"C","text":"1.15 × 10⁵ s"},{"id":"D","text":"1.15 × 10³ s"}]'::jsonb,correct_answer=to_jsonb('D'::text),question_type='mcq',is_active=true,answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='7c1d804b-c5d3-4917-bc4b-ff0e42ae488a' and correct_answer is null and source='storage:787b6ff8-b879-4c0d-b2dd-8b51c119446f';
update public.past_questions set question_text='When the length l of a piece of wire under constant tension is varied, the relationship between the frequency of vibration f and l is',options='[{"id":"A","text":"f ∝ l"},{"id":"B","text":"f ∝ 1/l²"},{"id":"C","text":"f ∝ √l"},{"id":"D","text":"f ∝ 1/l"}]'::jsonb,correct_answer=to_jsonb('D'::text),question_type='mcq',is_active=true,answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='4389a0f6-6d42-4e63-974e-6c5091e77bbc' and correct_answer is null and source='storage:787b6ff8-b879-4c0d-b2dd-8b51c119446f';
update public.past_questions set question_text='A vehicle of mass m is driven by an engine of power P from rest. Find the minimum time it will take to acquire a speed v.',options='[{"id":"A","text":"mv²/(2P)"},{"id":"B","text":"mv²/P"},{"id":"C","text":"mv/P"},{"id":"D","text":"mv/(2P)"}]'::jsonb,correct_answer=to_jsonb('A'::text),question_type='mcq',year=1995,is_active=true,answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='ec6e9787-81bf-458c-900a-c513a272e8d0' and correct_answer is null and source='storage:787b6ff8-b879-4c0d-b2dd-8b51c119446f';
update public.past_questions set question_text='A current of 100 mA passes through a conductor for 2 minutes. The quantity of electricity transported is',options='[{"id":"A","text":"200 C"},{"id":"B","text":"50 C"},{"id":"C","text":"12 C"},{"id":"D","text":"0.02 C"}]'::jsonb,correct_answer=to_jsonb('C'::text),question_type='mcq',year=1993,is_active=true,answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='c5832e1f-8420-45b1-b017-61c5fb341c1a' and correct_answer is null and source='storage:787b6ff8-b879-4c0d-b2dd-8b51c119446f';
update public.past_questions set question_text='Which of the following is true of magnetism?',options='[{"id":"A","text":"Iron filings cling mainly round the ends of a bar magnet"},{"id":"B","text":"A freely suspended bar magnet comes to rest in the geographic north-south direction"},{"id":"C","text":"Like poles attract"},{"id":"D","text":"Lodestone is a non-magnetic oxide"}]'::jsonb,correct_answer=to_jsonb('A'::text),question_type='mcq',year=1986,is_active=true,answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='c283b785-8b8d-41b9-85d2-c32ca3ed823c' and correct_answer is null and source='storage:787b6ff8-b879-4c0d-b2dd-8b51c119446f';
update public.past_questions set question_text='Which of the following are true for alpha decay? I. Mass number decreases by four. II. Atomic number decreases by two. III. Mass number does not change.',options='[{"id":"A","text":"I and II only"},{"id":"B","text":"II and III only"},{"id":"C","text":"I and III only"},{"id":"D","text":"I, II and III"}]'::jsonb,correct_answer=to_jsonb('A'::text),question_type='mcq',year=1991,is_active=true,answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='a6fdd7a3-e626-427c-b065-25654ae4897d' and correct_answer is null and source='storage:787b6ff8-b879-4c0d-b2dd-8b51c119446f';
update public.past_questions set question_text='A moving-coil galvanometer of 300 Ω resistance gives full-scale deflection for 1.0 mA. The resistance R of the shunt required to convert the galvanometer into a 3.0 A ammeter is',options='[{"id":"A","text":"899.70 Ω"},{"id":"B","text":"10.00 Ω"},{"id":"C","text":"0.10 Ω"},{"id":"D","text":"0.01 Ω"}]'::jsonb,correct_answer=to_jsonb('C'::text),question_type='mcq',year=1991,is_active=true,answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='cef815fd-96f3-47f5-a303-a9cffde1f6f5' and correct_answer is null and source='storage:787b6ff8-b879-4c0d-b2dd-8b51c119446f';
update public.past_questions set question_text='40 m³ of liquid P is mixed with 60 m³ of liquid Q. If the densities of P and Q are 1.00 kg m⁻³ and 1.6 kg m⁻³ respectively, what is the density of the mixture?',options='[{"id":"A","text":"0.05 kg m⁻³"},{"id":"B","text":"1.25 kg m⁻³"},{"id":"C","text":"1.30 kg m⁻³"},{"id":"D","text":"1.36 kg m⁻³"}]'::jsonb,correct_answer=to_jsonb('D'::text),question_type='mcq',year=1990,is_active=true,answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='40767db9-4062-4ffe-b010-5514af504a5d' and correct_answer is null and source='storage:787b6ff8-b879-4c0d-b2dd-8b51c119446f';
update public.past_questions set question_text='A bar of initial length l₀ is heated through a temperature change Δt to a new length l. The linear expansivity α of the bar is',options='[{"id":"A","text":"(l - l₀)/(lΔt)"},{"id":"B","text":"(l - l₀)/(l₀Δt)"},{"id":"C","text":"l₀(1 + Δt)"},{"id":"D","text":"(l - l₀)/[l(1 + Δt)]"}]'::jsonb,correct_answer=to_jsonb('B'::text),question_type='mcq',year=1990,is_active=true,answer_source='public-archive-cross-validation',answer_verified_at=now(),updated_at=now() where id='c0b486e7-a1c3-42ae-b30e-9345d610da5c' and correct_answer is null and source='storage:787b6ff8-b879-4c0d-b2dd-8b51c119446f';
