-- Safely deepen strict JAMB CBT from existing Supabase Storage source papers only.
-- No seeded/generated JAMB rows are introduced.

-- Chemistry: validate ten clean archived MCQs.
update public.past_questions set correct_answer=to_jsonb('A'::text),answer_source='manual-content-validation',answer_verified_at=now(),updated_at=now() where id='00d8ec9e-3d53-47e0-b648-31d5874dba1b' and correct_answer is null and source like 'storage:%';
update public.past_questions set correct_answer=to_jsonb('C'::text),answer_source='manual-content-validation',answer_verified_at=now(),updated_at=now() where id='00fdd110-b1d1-4144-833a-42b469b56672' and correct_answer is null and source like 'storage:%';
update public.past_questions set correct_answer=to_jsonb('B'::text),answer_source='manual-content-validation',answer_verified_at=now(),updated_at=now() where id='04587575-5846-441f-aeb4-a102fb7508a3' and correct_answer is null and source like 'storage:%';
update public.past_questions set correct_answer=to_jsonb('B'::text),answer_source='manual-content-validation',answer_verified_at=now(),updated_at=now() where id='046fd54c-43b2-490b-87f5-d01450a3188d' and correct_answer is null and source like 'storage:%';
update public.past_questions set correct_answer=to_jsonb('C'::text),answer_source='manual-content-validation',answer_verified_at=now(),updated_at=now() where id='04aa98c0-6d62-4a49-af4c-84ad0420be61' and correct_answer is null and source like 'storage:%';
update public.past_questions set correct_answer=to_jsonb('E'::text),answer_source='manual-content-validation',answer_verified_at=now(),updated_at=now() where id='062ba463-05a4-4ef7-b113-8bf4bb91817e' and correct_answer is null and source like 'storage:%';
update public.past_questions set correct_answer=to_jsonb('D'::text),answer_source='manual-content-validation',answer_verified_at=now(),updated_at=now() where id='06b976df-f1b4-4dd9-9ce0-902d32df3a82' and correct_answer is null and source like 'storage:%';
update public.past_questions set correct_answer=to_jsonb('A'::text),answer_source='manual-content-validation',answer_verified_at=now(),updated_at=now() where id='0958cbd4-f8f4-4f62-85af-71a8d0b947a4' and correct_answer is null and source like 'storage:%';
update public.past_questions set correct_answer=to_jsonb('D'::text),answer_source='manual-content-validation',answer_verified_at=now(),updated_at=now() where id='09608942-b083-42bf-8d60-c941ce9f64b9' and correct_answer is null and source like 'storage:%';
update public.past_questions set correct_answer=to_jsonb('A'::text),answer_source='manual-content-validation',answer_verified_at=now(),updated_at=now() where id='0cdddd99-2fb3-4d92-afa2-70b740dcd9dd' and correct_answer is null and source like 'storage:%';

-- Biology: validate ten archived MCQs and remove obvious OCR spillover on the activated rows.
update public.past_questions set question_text='If a nursing mother is not producing enough milk, her hormonal system is probably deficient in',options='[{"id":"A","text":"testosterone"},{"id":"B","text":"thyroxin"},{"id":"C","text":"insulin"},{"id":"D","text":"prolactin"}]'::jsonb,correct_answer=to_jsonb('D'::text),answer_source='manual-content-validation',answer_verified_at=now(),updated_at=now() where id='0267f10d-64ca-473a-bb1b-3e2cd1144b70' and correct_answer is null and source like 'storage:%';
update public.past_questions set question_text='When a short-sighted person views a distant object without spectacles, the image is formed',options='[{"id":"A","text":"on the retina"},{"id":"B","text":"in front of the retina"},{"id":"C","text":"behind the retina"},{"id":"D","text":"on the blind spot"}]'::jsonb,correct_answer=to_jsonb('B'::text),answer_source='manual-content-validation',answer_verified_at=now(),updated_at=now() where id='04e5e9ce-056d-4df6-af7b-b512c261bbe5' and correct_answer is null and source like 'storage:%';
update public.past_questions set options='[{"id":"A","text":"blue and wrinkled"},{"id":"B","text":"round and yellow"},{"id":"C","text":"wrinkled and yellow"},{"id":"D","text":"round and greenish-yellow"}]'::jsonb,correct_answer=to_jsonb('B'::text),answer_source='manual-content-validation',answer_verified_at=now(),updated_at=now() where id='04f10f09-7ee8-4a3a-898f-ef79cd38064e' and correct_answer is null and source like 'storage:%';
update public.past_questions set question_text='A fundamental similarity between nervous and hormonal systems is that both',options='[{"id":"A","text":"involve chemical transmission"},{"id":"B","text":"have widespread effects"},{"id":"C","text":"shed chemicals into the bloodstream"},{"id":"D","text":"evoke rapid responses"}]'::jsonb,correct_answer=to_jsonb('A'::text),answer_source='manual-content-validation',answer_verified_at=now(),updated_at=now() where id='052fa234-85d1-4096-830d-860d67b81cc4' and correct_answer is null and source like 'storage:%';
update public.past_questions set question_text='The surface of an alveolus in a mammal is well supplied with tiny blood vessels known as',options='[{"id":"A","text":"capillaries"},{"id":"B","text":"arteries"},{"id":"C","text":"arterioles"},{"id":"D","text":"venules"}]'::jsonb,correct_answer=to_jsonb('A'::text),answer_source='manual-content-validation',answer_verified_at=now(),updated_at=now() where id='0ddc13c1-ad34-4ab3-aadd-1bea31c85e4a' and correct_answer is null and source like 'storage:%';
update public.past_questions set options='[{"id":"A","text":"has flagella"},{"id":"B","text":"has plant and animal features"},{"id":"C","text":"is found in water"},{"id":"D","text":"can manufacture its food"},{"id":"E","text":"moves fast"}]'::jsonb,correct_answer=to_jsonb('D'::text),answer_source='manual-content-validation',answer_verified_at=now(),updated_at=now() where id='0eb3100d-2e41-4b5a-922a-aa82f54b785d' and correct_answer is null and source like 'storage:%';
update public.past_questions set question_text='The movement of the whole organism in response to an external stimulus is termed',correct_answer=to_jsonb('B'::text),answer_source='manual-content-validation',answer_verified_at=now(),updated_at=now() where id='1068ecb2-7d86-4ff7-92b3-935cc643d1c6' and correct_answer is null and source like 'storage:%';
update public.past_questions set correct_answer=to_jsonb('C'::text),answer_source='manual-content-validation',answer_verified_at=now(),updated_at=now() where id='14a99676-fbc8-4008-b4a3-87748a4becc5' and correct_answer is null and source like 'storage:%';
update public.past_questions set question_text='Severe diarrhoea, dehydration and weakness are symptoms of',options='[{"id":"A","text":"cholera"},{"id":"B","text":"chickenpox"},{"id":"C","text":"malaria"},{"id":"D","text":"yellow fever"}]'::jsonb,correct_answer=to_jsonb('A'::text),answer_source='manual-content-validation',answer_verified_at=now(),updated_at=now() where id='1b39ebbf-f3cf-43bf-90c8-1a6ae2dd2df7' and correct_answer is null and source like 'storage:%';
update public.past_questions set correct_answer=to_jsonb('D'::text),answer_source='manual-content-validation',answer_verified_at=now(),updated_at=now() where id='34e0d990-7889-4d80-97be-0af331d10384' and correct_answer is null and source like 'storage:%';
