'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { BookOpen, CheckCircle2, Clock3, FolderOpen, GraduationCap, Loader2, Play, Search } from 'lucide-react';
import { getSupabase } from '@/lib/supabase';
import { useAuth } from '@/contexts/AuthContext';

type Lesson = { id:string; course_id:string; title:string; slug:string|null; description:string|null; is_published:boolean; estimated_minutes:number|null; order_index:number; topic_id:string|null };
type Course = { id:string; title:string; slug:string; subject_id:string|null; class_id:string; lessons:Lesson[] };
type ClassRow = { id:string; name:string; code:string; order_index:number };
type Subject = { id:string; name:string; order_index:number };
type ClassGroup = { key:string; label:string; level:string; courses:Course[] };

function levelFromClass(c:ClassRow){ const code=c.code.toUpperCase().replace(/-A$|-B$/,''); const m=code.match(/^(P|JSS|SSS?)(\d)/); if(!m)return null; const prefix=m[1]; const n=m[2]; if(prefix==='P')return `Primary ${n}`; if(prefix==='JSS')return `JSS ${n}`; return `SS ${n}`; }
function levelOrder(level:string){ const m=level.match(/(Primary|JSS|SS) (\d)/); if(!m)return 999; return (m[1]==='Primary'?0:m[1]==='JSS'?10:20)+Number(m[2]); }

export default function LessonsPage(){
 const {token}=useAuth(); const [groups,setGroups]=useState<ClassGroup[]>([]); const [subjects,setSubjects]=useState<Subject[]>([]); const [loading,setLoading]=useState(true); const [search,setSearch]=useState(''); const [error,setError]=useState(''); const [selectedLevel,setSelectedLevel]=useState('All');
 useEffect(()=>{ if(!token)return; let cancelled=false; (async()=>{setLoading(true);setError('');try{const s=getSupabase(); const [{data:classes,error:ce},{data:subs,error:se}]=await Promise.all([s.from('classes').select('id,name,code,order_index').eq('is_active',true).order('order_index').order('name'),s.from('subjects').select('id,name,order_index').eq('is_active',true).order('order_index').order('name')]); if(ce)throw ce;if(se)throw se; const valid=(classes||[]).map((c:any)=>({...c,level:levelFromClass(c)})).filter((c:any)=>c.level); const courseRows:any[]=[]; for(const c of valid){const {data,error}=await s.from('courses').select('id,title,slug,subject_id,class_id').eq('class_id',c.id).eq('status','published').order('title');if(error)throw error;(data||[]).forEach((x:any)=>courseRows.push({...x,class_level:c.level}));} const ids=courseRows.map(x=>x.id); const {data:ls,error:le}=ids.length?await s.from('lessons').select('id,course_id,title,slug,description,is_published,estimated_minutes,order_index,topic_id').in('course_id',ids).eq('is_published',true).order('order_index'):{data:[],error:null} as any;if(le)throw le; const by=new Map<string,Lesson[]>();(ls||[]).forEach((l:any)=>by.set(l.course_id,[...(by.get(l.course_id)||[]),l])); const map=new Map<string,ClassGroup>();courseRows.forEach(c=>{if(!(by.get(c.id)||[]).length)return;const key=c.class_level;const old=map.get(key);const course={...c,lessons:by.get(c.id)||[]};if(old)old.courses.push(course);else map.set(key,{key,label:key,level:key,courses:[course]});}); const result=[...map.values()].sort((a,b)=>levelOrder(a.level)-levelOrder(b.level)); if(!cancelled){setGroups(result);setSubjects((subs||[]) as Subject[]);}}catch(e:any){if(!cancelled)setError(e?.message||'Unable to load the curriculum.')}finally{if(!cancelled)setLoading(false)}})();return()=>{cancelled=true}},[token]);
 const levels=['All','Primary 1','Primary 2','Primary 3','Primary 4','Primary 5','Primary 6','JSS 1','JSS 2','JSS 3','SS 1','SS 2','SS 3'];
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return groups.filter(g=>selectedLevel==='All'||g.level===selectedLevel).map(g=>({...g,courses:g.courses.filter(c=>{const subject=subjects.find(s=>s.id===c.subject_id)?.name||'';return !q||`${c.title} ${subject} ${g.level}`.toLowerCase().includes(q)||c.lessons.some(l=>`${l.title} ${l.description||''}`.toLowerCase().includes(q));})})).filter(g=>g.courses.length)},[groups,subjects,search,selectedLevel]);
 const total=groups.reduce((n,g)=>n+g.courses.reduce((x,c)=>x+c.lessons.length,0),0);
 if(loading)return <div className="flex min-h-[50vh] items-center justify-center"><Loader2 className="h-8 w-8 animate-spin text-[#151A3A]"/></div>;
 return <div className="space-y-6"><header><div className="flex items-center gap-2 text-sm font-semibold text-brand-700"><GraduationCap className="h-5 w-5"/>THE GUIDE Curriculum</div><h1 className="mt-2 text-3xl font-extrabold text-[#151A3A] dark:text-white">Lessons & Teaching</h1><p className="mt-1 text-slate-500 dark:text-slate-400">Learn progressively from Primary 1 through SS3. Every published lesson is followed by practice and progress.</p></header>
 <div className="rounded-2xl border border-stone-200 bg-white p-4 shadow-sm dark:border-slate-700 dark:bg-[#1b2045]"><div className="flex flex-wrap gap-2">{levels.map(l=><button key={l} onClick={()=>setSelectedLevel(l)} className={`rounded-xl px-3 py-2 text-sm font-semibold ${selectedLevel===l?'bg-[#151A3A] text-white':'bg-stone-50 text-slate-600 hover:bg-brand-50 dark:bg-[#151A3A] dark:text-slate-300'}`}>{l}</button>)}</div><div className="relative mt-4 max-w-xl"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search class, subject, topic or lesson…" className="w-full rounded-xl border border-stone-200 bg-stone-50 py-3 pl-9 pr-4 text-sm outline-none focus:border-brand-500 dark:border-slate-700 dark:bg-[#151A3A] dark:text-white"/></div></div>
 {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
 {!filtered.length?<div className="rounded-2xl border border-dashed border-stone-300 bg-white p-12 text-center dark:border-slate-700 dark:bg-[#1b2045]"><BookOpen className="mx-auto h-12 w-12 text-stone-300"/><h2 className="mt-4 font-bold text-[#151A3A] dark:text-white">No published lessons for this level yet</h2><p className="mt-2 text-sm text-slate-500">The class remains available in the curriculum; lessons will appear as they are published.</p></div>:<div className="space-y-8">{filtered.map(group=><section key={group.key} className="overflow-hidden rounded-2xl border border-stone-200 bg-white shadow-sm dark:border-slate-700 dark:bg-[#1b2045]"><div className="flex items-center gap-3 border-b border-stone-200 bg-stone-50 px-5 py-4 dark:border-slate-700 dark:bg-[#151A3A]"><GraduationCap className="h-5 w-5 text-brand-600"/><div><h2 className="text-xl font-bold text-[#151A3A] dark:text-white">{group.label}</h2><p className="text-xs text-slate-500">{group.courses.length} subject course{group.courses.length===1?'':'s'}</p></div></div><div className="space-y-5 p-4 sm:p-5">{group.courses.map(course=>{const subject=subjects.find(s=>s.id===course.subject_id)?.name||course.title;return <div key={course.id} className="rounded-xl border border-stone-200 dark:border-slate-700"><div className="flex items-center gap-3 bg-stone-50 px-4 py-3 dark:bg-[#151A3A]"><FolderOpen className="h-5 w-5 text-brand-600"/><div><h3 className="font-bold text-[#151A3A] dark:text-white">{subject}</h3><p className="text-xs text-slate-500">{course.title} · {course.lessons.length} lessons</p></div></div><div className="divide-y divide-stone-100 dark:divide-slate-700">{course.lessons.map((lesson,i)=><Link key={lesson.id} href={`/dashboard/lessons/${course.slug||course.id}/${lesson.slug||lesson.id}`} className="flex items-center gap-3 px-4 py-4 transition hover:bg-brand-50/60 dark:hover:bg-slate-800"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-stone-100 text-xs font-bold text-slate-600 dark:bg-slate-800 dark:text-slate-300">{i+1}</span><Play className="h-4 w-4 shrink-0 text-brand-600"/><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-slate-900 dark:text-white">{lesson.title}</p><p className="truncate text-xs text-slate-500">{lesson.description||'Open to learn, practise and continue.'}</p></div><span className="hidden items-center gap-1 text-xs text-slate-400 sm:flex"><Clock3 className="h-3 w-3"/>{lesson.estimated_minutes||10} min</span><CheckCircle2 className="h-4 w-4 text-emerald-500"/></Link>)}</div></div>})}</div></section>)}</div>}
 <p className="text-center text-xs text-slate-400">{total} published lessons available across the curriculum.</p></div>;
}
