'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { BookOpen, CheckCircle2, Clock3, FolderOpen, GraduationCap, Loader2, Play, Search, Sparkles } from 'lucide-react';
import { getSupabase } from '@/lib/supabase';
import { useAuth } from '@/contexts/AuthContext';

type Lesson={id:string;course_id:string;title:string;slug:string|null;description:string|null;is_published:boolean;estimated_minutes:number|null;order_index:number;topic_id:string|null};
type Course={id:string;title:string;slug:string;subject_id:string|null;class_id:string;lessons:Lesson[]};
type ClassRow={id:string;name:string;code:string;order_index:number};
type Subject={id:string;name:string;order_index:number};
type ClassGroup={level:string;courses:Course[]};

const LEVELS=['All','Primary 1','Primary 2','Primary 3','Primary 4','Primary 5','Primary 6','JSS 1','JSS 2','JSS 3','SS 1','SS 2','SS 3'];
function levelFromClass(c:ClassRow){const code=c.code.toUpperCase().replace(/-A$|-B$/,'');const m=code.match(/^(P|JSS|SSS?)(\d)/);if(!m)return null;const n=m[2];return m[1]==='P'?`Primary ${n}`:m[1]==='JSS'?`JSS ${n}`:`SS ${n}`;}
function levelOrder(level:string){const m=level.match(/(Primary|JSS|SS) (\d)/);if(!m)return 999;return(m[1]==='Primary'?0:m[1]==='JSS'?10:20)+Number(m[2]);}

export default function LessonsPage(){
 const {token}=useAuth();const [groups,setGroups]=useState<ClassGroup[]>([]);const [subjects,setSubjects]=useState<Subject[]>([]);const [loading,setLoading]=useState(true);const [search,setSearch]=useState('');const [selectedLevel,setSelectedLevel]=useState('All');const [error,setError]=useState('');
 useEffect(()=>{if(!token)return;let cancelled=false;(async()=>{setLoading(true);setError('');try{const s=getSupabase();const [{data:classes,error:ce},{data:subs,error:se}]=await Promise.all([s.from('classes').select('id,name,code,order_index').eq('is_active',true).order('order_index').order('name'),s.from('subjects').select('id,name,order_index').eq('is_active',true).order('order_index').order('name')]);if(ce)throw ce;if(se)throw se;const valid=(classes||[]).map((c:any)=>({...c,level:levelFromClass(c)})).filter((c:any)=>c.level);const rows:any[]=[];for(const c of valid){const {data,error}=await s.from('courses').select('id,title,slug,subject_id,class_id').eq('class_id',c.id).eq('status','published').order('title');if(error)throw error;(data||[]).forEach((x:any)=>rows.push({...x,class_level:c.level}));}const ids=rows.map(x=>x.id);const {data:ls,error:le}=ids.length?await s.from('lessons').select('id,course_id,title,slug,description,is_published,estimated_minutes,order_index,topic_id').in('course_id',ids).eq('is_published',true).order('order_index'):{data:[],error:null} as any;if(le)throw le;const by=new Map<string,Lesson[]>();(ls||[]).forEach((l:any)=>by.set(l.course_id,[...(by.get(l.course_id)||[]),l]));const map=new Map<string,ClassGroup>();rows.forEach(c=>{const lessons=by.get(c.id)||[];if(!lessons.length)return;const old=map.get(c.class_level);const course={...c,lessons};if(old)old.courses.push(course);else map.set(c.class_level,{level:c.class_level,courses:[course]});});const result=[...map.values()].sort((a,b)=>levelOrder(a.level)-levelOrder(b.level));if(!cancelled){setGroups(result);setSubjects((subs||[]) as Subject[]);}}catch(e:any){if(!cancelled)setError(e?.message||'Unable to load the curriculum.')}finally{if(!cancelled)setLoading(false)}})();return()=>{cancelled=true}},[token]);
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return groups.filter(g=>selectedLevel==='All'||g.level===selectedLevel).map(g=>({...g,courses:g.courses.filter(c=>{const subject=subjects.find(s=>s.id===c.subject_id)?.name||'';return !q||`${c.title} ${subject} ${g.level}`.toLowerCase().includes(q)||c.lessons.some(l=>`${l.title} ${l.description||''}`.toLowerCase().includes(q));})})).filter(g=>g.courses.length)},[groups,subjects,search,selectedLevel]);
 const published=groups.reduce((n,g)=>n+g.courses.reduce((x,c)=>x+c.lessons.length,0),0);const available=new Set(groups.map(g=>g.level));
 if(loading)return <div className="flex min-h-[55vh] items-center justify-center"><Loader2 className="h-8 w-8 animate-spin text-[#151A3A]"/></div>;
 return <div className="space-y-7">
  <section className="overflow-hidden rounded-3xl bg-[#151A3A] p-6 text-white shadow-xl sm:p-8"><div className="flex flex-col gap-6 md:flex-row md:items-end md:justify-between"><div><div className="mb-3 inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1.5 text-xs font-bold"><Sparkles className="h-4 w-4"/>THE GUIDE CURRICULUM</div><h1 className="text-3xl font-extrabold tracking-tight sm:text-4xl">Learn from Primary 1 to SS 3</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-300">A structured learning path: teaching first, practice questions as you progress, then continue to the next lesson.</p></div><div className="rounded-2xl bg-white/10 p-4"><GraduationCap className="h-10 w-10"/><p className="mt-2 text-xs text-slate-300">{published} published lessons</p></div></div></section>
  <section className="grid gap-3 sm:grid-cols-3"><button onClick={()=>setSelectedLevel('Primary 1')} className={`rounded-2xl border p-5 text-left ${selectedLevel.startsWith('Primary')?'border-[#151A3A] bg-[#151A3A] text-white':'border-stone-200 bg-white dark:border-slate-700 dark:bg-[#1b2045] dark:text-white'}`}><div className="text-2xl">📚</div><p className="mt-2 font-bold">Primary School</p><p className="text-sm opacity-70">Primary 1–6</p></button><button onClick={()=>setSelectedLevel('JSS 1')} className={`rounded-2xl border p-5 text-left ${selectedLevel.startsWith('JSS')?'border-[#151A3A] bg-[#151A3A] text-white':'border-stone-200 bg-white dark:border-slate-700 dark:bg-[#1b2045] dark:text-white'}`}><div className="text-2xl">🎓</div><p className="mt-2 font-bold">Junior Secondary</p><p className="text-sm opacity-70">JSS 1–3</p></button><button onClick={()=>setSelectedLevel('SS 1')} className={`rounded-2xl border p-5 text-left ${selectedLevel.startsWith('SS')?'border-[#151A3A] bg-[#151A3A] text-white':'border-stone-200 bg-white dark:border-slate-700 dark:bg-[#1b2045] dark:text-white'}`}><div className="text-2xl">🚀</div><p className="mt-2 font-bold">Senior Secondary</p><p className="text-sm opacity-70">SS 1–3</p></button></section>
  <section className="rounded-2xl border border-stone-200 bg-white p-4 shadow-sm dark:border-slate-700 dark:bg-[#1b2045]"><div className="flex flex-wrap gap-2">{LEVELS.map(l=><button key={l} onClick={()=>setSelectedLevel(l)} className={`rounded-xl px-3 py-2 text-sm font-semibold ${selectedLevel===l?'bg-[#151A3A] text-white':'bg-stone-50 text-slate-600 hover:bg-stone-100 dark:bg-[#151A3A] dark:text-slate-300'}`}>{l}</button>)}</div><div className="relative mt-4 max-w-2xl"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search subjects, topics or lessons…" className="w-full rounded-xl border border-stone-200 bg-stone-50 py-3 pl-9 pr-4 text-sm outline-none focus:border-[#151A3A] dark:border-slate-700 dark:bg-[#151A3A] dark:text-white"/></div></section>
  {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
  {!filtered.length?<div className="rounded-2xl border border-dashed border-stone-300 bg-white p-12 text-center dark:border-slate-700 dark:bg-[#1b2045]"><BookOpen className="mx-auto h-12 w-12 text-stone-300"/><h2 className="mt-4 font-bold text-[#151A3A] dark:text-white">No published lessons here yet</h2><p className="mt-2 text-sm text-slate-500">This class is part of THE GUIDE curriculum, but course lessons have not been published for it yet.</p></div>:<div className="space-y-8">{filtered.map(g=><section key={g.level} className="overflow-hidden rounded-2xl border border-stone-200 bg-white shadow-sm dark:border-slate-700 dark:bg-[#1b2045]"><div className="flex items-center gap-3 border-b border-stone-200 bg-stone-50 px-5 py-4 dark:border-slate-700 dark:bg-[#151A3A]"><GraduationCap className="h-5 w-5 text-brand-600"/><div><h2 className="text-xl font-bold text-[#151A3A] dark:text-white">{g.level}</h2><p className="text-xs text-slate-500">{g.courses.length} subject course{g.courses.length===1?'':'s'}</p></div></div><div className="grid gap-4 p-4 sm:grid-cols-2 lg:grid-cols-3">{g.courses.map(c=>{const subject=subjects.find(s=>s.id===c.subject_id)?.name||c.title;return <Link key={c.id} href={`/dashboard/lessons/${c.slug||c.id}`} className="group rounded-xl border border-stone-200 bg-white p-5 transition hover:-translate-y-1 hover:shadow-md dark:border-slate-700 dark:bg-[#1b2045]"><div className="flex items-center gap-3"><div className="rounded-xl bg-brand-50 p-3 dark:bg-brand-950"><FolderOpen className="h-5 w-5 text-brand-700 dark:text-brand-300"/></div><div className="min-w-0"><h3 className="truncate font-bold text-[#151A3A] dark:text-white">{subject}</h3><p className="text-xs text-slate-500">{c.lessons.length} lessons</p></div></div><p className="mt-4 line-clamp-2 text-sm text-slate-500">{c.title}</p><div className="mt-4 flex items-center justify-between text-xs font-semibold text-[#151A3A] dark:text-white"><span className="inline-flex items-center gap-1"><Play className="h-3.5 w-3.5"/>Start learning</span><span>{c.lessons.length} lessons</span></div></Link>})}</div></section>)}</div>}
  <div className="flex flex-wrap justify-center gap-2 text-center text-xs text-slate-400">{LEVELS.slice(1).map(l=><span key={l} className={`rounded-full px-2 py-1 ${available.has(l)?'bg-emerald-50 text-emerald-700 dark:bg-emerald-950/30 dark:text-emerald-300':'bg-stone-100 dark:bg-slate-800'}`}>{l} {available.has(l)?'• content':'• awaiting content'}</span>)}</div>
 </div>;
}
